# ACKNOWLEDGEMENTS / DISCLAIMERS {-}

---

---

## Acknowledgments {-}
Thank you to all that have participated providing recipes for this book. Recipes have been contributed by family and friends and by many that might not know that we sneaked their recipes, but good food is worth copying.

## Disclaimer {-}
If there is something you didn’t like, you must have made it wrong because we do not make mistakes and we certainly have great taste. Typing was done by Alvin Spencer who has no ability to spell, count, type or duplicate. All complaints must be directed to his email Trash Bin within 30 days from the date the recipe was typed.

## COOK and ENJOY {-}

---

# NOTES {- #notes} 

---

## What’s the Difference Between Chop, Dice, and Mince? {-}

### I don't know but try these comments {-}
Sometimes the words chop and dice are used interchangeably, but technically the word dice is used for smaller pieces and the word chop is used for larger pieces. You seldom see the term large dice, but you will see large chop and small dice rather frequently. Dice can also refer to cutting vegetable into cubes of a specific size while chop is less precise. In general, chop is more casual and has more leeway while dice is more specific. The word mince means a very small dice.

### How Big is a Dice? How Small is a Mince? {-}
How do you know how big or small something is supposed to be? If the recipe writer feels it matters, usually they will also include a measurement, like 3/4" dice. Again, we see the word dice here to indicate that this is a very specific direction. But if the sizing has some leeway, they will say either large, medium or small chop. Unfortunately, these sizes aren’t standardized so it’s hard to give measurements.

- Large chop – For me, when a recipe says large chop, I usually make it roughly the size of a nickel.
- 
- Medium Chop – Medium chop is about half the size of a nickel.
- 
- Diced (Small Chop) – Small chop is about half of medium chop, perhaps a quarter inch to a side.
- 
- Minced – Mince is very fine, as small as I can get it.

---

# Appetizers and Beverages {#appetizers}

---

---

## ARTICHOKE DIP {-}

### Chef: Debbie Wescott {-}

### Ingredients {-}
- 2 8oz packages of cream cheese - softened
- 1/2 cup mayonnaise
- 3 to 5 cloves of garlic - or 3 tablespoons of Minced garlic
- 14 oz can artichoke hearts - drained and chopped, marinated
- 10 oz package of frozen spinach - softened
- 2 tablespoons of lemon juice
- 1/2 cup grated parmesan cheese
- 1 cup of mozzoretta cheese - grated

### Directions {-}
Cream the cream cheese, mayonnaise and garlic together and set aside. Mix remaining ingredients down the list to Parmesan cheese. Combine parts 1 and 2 and spread into a baking dish. Bake at 375° for 20 minutes then layer on Mozzoretta cheese, Bake 5 more minutes until light golden brown. Serve with fresh veggies or crackers. YUM!

---

## COWBOY CAVIAR {-}

### Chef: Patricia Blair {-}

### Ingredients {-}
- 15oz can black eyed peas - drained
- 15oz can [shoepeg corn](https://en.wikipedia.org/wiki/Shoepeg_corn) - drained
- 2/3 cup cilantro - chopped
- 2/3 cup green onion - chopped
- 1/4 cup olive oil dressing
- 1/4 cup red wine vinegar
- 2 cloves garlic - minced
- 3/4 teaspoon salt
- 1/8 teaspoon pepper
- 1/2 teaspoon cumin
- 2 large tomatoes - diced
- 2 avacados - diced

### Directions {-}
Except the tomatoes and avacados marinate all other ingredients together for 6+ hours. Add diced tomatoes and avacados 30 minutes before serving.

---

## CREAM OF COCONUT FRUIT DIP {-}

### Chef: Jennifer Gustin {-}

### Ingredients {-}
- 1 package instant vanilla pudding (4.6 oz)
- 1 container cream of coconut (found in alcohol mix section)
- 16 oz whipped cream (Cool Whip)

### Directions {-}
Combine all three ingredients together and chill for one hour so pudding dissolves completely. 
Serve with fruit. Great with sliced apple.

---

## CUCUMBER SANDWICHES {-}

### Chef: Patricia Blair {-}

### Ingredients {-}
- 8 oz cream cheese
- 2 tablespoons mayonnaise
- 2 green onions - diced
- 1/2 teaspoon [Bon Appettit](https://www.mccormick.com/gourmet/recipes/other/bon-appetit-seasoning-replacement) seasoning 
- 1/2 teaspoon dill weed
- 1/2 teaspoon garlic salt
- cucumbers - peeled and sliced
- tomatoes - sliced
- bread - crust removed

### Directions {-}
Combine together: cream cheese, mayonnaise, green onions, Bon Appettit, dill weed, and garlic salt. 
Spread mixture on bread and layer with sliced cucumber and tomato. Cover and refrigerate until ready to use.

---

## DAD'S SUNDAY EVENING POPCORN {-}

### Chef: Alvin Spencer {-}

### Ingredients {-}
- 1/2 cup of popcorn - uncooked
- 1 to 3 teaspoons of olive oil
- 1/4 cup of butter or margerine 
- 1/4 teaspoon of popcorn salt

### Directions {-}
Best cooked in a [Whirley-pop](https://www.whirleypopshop.com/) popcorn popper. This requires only 1 teaspoon of oil.  
Cook over medium high heat until kernels stop popping or until smoke fills the kitchen. 
Place in a large bowel and sprinkle melted butter lightly over popcorn while stirring. Olive oil can be substituted for margarine. 
Sprinkle salt over popcorn and stir. Eat while warm and while watching a good movie with the family gathered around you. 

---

## FIVE LAYER AVOCADO DIP {-}

### Chef: Patricia Blair {-}

### Ingredients {-}
- 1 can refried beans
- 1 can chip bean dip
- 2 large avocados - mashed
- 1 small can green chilies - diced
- 1/2 pint sour cream
- 1/4 jar favorite salsa
- garlic / onion salt and pepper
- 1/2 cup green onions - chopped
- 1 can sliced black olives
- 1 lb. favorite shredded cheese

### Directions {-}
Layer in 9x13 pan. 
 --  First Layer: 1 can refried beans and 1 can chip bean dip. 
 --  Second Layer (Mix together) avocados, green chilies, sour cream, salsa, seasonings. 
 --  Third Layer: Green onions, 
 --  Fourth Layer: sliced olives. 
 --  Fifth Layer: cheese. 
 
 Serve with chips

---

## HOT BUTTERED 'RUM' DRINK {-}

### Chef: Jennifer Gustin {-}

### Ingredients {-}
- 1 1/2 cups brown sugar
- 1 3/4 cups powdered sugar
- 2 pints vanilla ice-cream
- 1/2 teaspoon nutmeg
- 1 teaspoon cinnamon

### Directions {-}
Soften ice-cream 30 minutes in refrigerator. Mix dry ingredients together. 
Cream together dry ingredients with softened ice-cream. 
Store in freezer. To serve, use 1 1/2  tsp of batter to a cup of hot water or milk. Add more to taste.

---

## HOT CHOCOLATE MIX {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 1 25.6 oz package of instant nonfat dry milk (10 2/3 cups)
- 1 6 oz jar powdered non-dairy creamer
- 2 cups powdered sugar
- 1 16 oz can instant chocolate drink mix

### Directions {-}
Combine all ingredients, Mix well. Put in a large air tight container. 
Label. Store in cool, dry place. Use within 6 months. Makes about 17 cups of hot chocolate mix.

-- For hot chocolate --  add 3 tablespoons of mix to 1 cup hot water.

---

## JALAPENO POPPER DIP {-}

### Chef: Jennifer Gustin {-}

### Ingredients {-}
- 2 packages light cream cheese
- 1 cup mahyonnaise
- 4 oz chopped green chillies
- 3 finely chopped jalepenos (The more seeds you use the spicier it is)
- 1 cup parmesan cheese
- 1 cup [panko bread crumbs](https://en.wikipedia.org/wiki/Bread_crumbs#Panko)

### Directions {-}
Stir together cream cheese and mayonnaise until smooth. Stir in green chilies and jalapenos. Pour mixture into oven-safe dish (8X8 works well) and sprinkle with parmesan cheese and bread crumbs.

---

## ORANGE JULIUS DRINK {-}

### Chef: Lori Hilton {-}

### Ingredients {-}
- 1/2 cup concentrated orange juice
- 3/4 cup milk
- 1 egg
- 1/2 teaspoon vanilla
- 1/4 cup sugar
- 1 1/2 cups ice

### Directions {-}
Put all ingredients in a blender and blend until ice is broken up smooth. 
Alter amount of ice to change consistency of the drink.

---

## TORTILLLA  APPETIZER {-}

### Chef: Patricia Blair {-}

### Ingredients {-}
- 8 oz cream cheese
- 3 green onions - diced
- 4  oz can diced green chilies
- 1 teaspoon garlic salt
- Olives - cut (desired amount)
- Cheddar cheese - shreaded (desired amount)
- Flour tortillas
- Toothpicks

### Directions {-}
Combine all ingredients. Spread mixture on tortillas. Roll tortilla up and slice into desired thickness.
hold together with a toothpick.

---

## WARM CREAMY BACON DIP {-}

### Chef: Debbie Wescott {-}

### Ingredients {-}
- 1 16 oz sour cream
- 1 3 oz bacon bits (or make your own)
- 2 cups grated cheddar or cheddar jack cheese
- 1 cup diced green onions

### Directions {-}
Heat oven to 400 deg. Combine all ingredients. 
Spread in a 1 quart baking dish. Heat 25 – 30 minutes until hot. 
Serve with veggies or crackers.
Great served in a bread bowl. Easy to double recipe!

---

## WEDDING PUNCH {-}

### Chef: Patricia Blair {-}

### Ingredients {-}
- 1 can frozen orange juice - large
- 1 can frozen lemonade - large
- 1 cup of sugar
- 1 teaspoon vanilla extract
- 1 gallon water
- 1 2 liter bottle 7-up

### Directions {-}
Mix all the ingredients EXCEPT the 7-up. Freeze in freezer bags.

-- To serve --  soften slightly, put in punch bowl, add the bottle of 7-up.

---

# Soups and Salads {#soup #salad}

---

---

## BLACK BEAN SOUP {-}

### Chef: Patricia Blair {-}

### Ingredients {-}
- 2 16oz cans black beans - undrained
- 1 cup reduced sodium chicken broth
- 1 small onion - chopped
- 1 teaspoon garlic - minced
- 1 16oz jar salsa - thick and chuncky
- 4 teaspoons lime juice
- 2 teaspoons ground cumin
- 1/4 teaspoon crushed red pepper (optional)
- 1/3 cup plain yogurt (optional)
- fresh cilantro leaves - chopped (optional)
- nonstick cooking spray

### Directions {-}
Place 1 can of beans with liquid and chicken broth in blender or food processor, cover, blend until smooth. 
Coat large saucepan with cooking spray, heat over medium – high heat. Add onion and garlic: cook for 4 to 5 minutes or until onion is tender. 
Add blended bean mixture, remaining beans and liquid, salsa, lime juice, cumin, and crushed red pepper. 
Bring to boil. Reduce heat to low and cover. Cook, stirring occasionally for 25 to 30 minutes. Serve topped with yogurt, garnish with cilantro.

---

## BROCOLI SALAD {-}

### Chef: Jennifer Gustin {-}

### Ingredients {-}
- 2 bunches broccoli
- 1/2/ red onion - chopped
- 1/4 lb bacon
- 3 oz sunflower seeds
- 1/2 cup raisins
- 1 cup light mayonnaise
- 1/2 cup sugar
- 2 tablespoons white vinegar

### Directions {-}
Cut broccoli into bite size pieces, Chop onion, Cook Bacon and crumble. 
Combine Broccoli, onion, bacon, and raisons in bowel. 
In separate bowl, mix mayonnaise, sugar, and vinegar. Toss with salad. 
Marinate in refrigerator for one hour. 
Mix in sunflower seeds before serving.

---

## BROCOLI, CHEESE AND POTATO SOUP {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 4 medium potatoes - peeled and diced
- 4 carrots - peeled and sliced
- 1 stalk celery - diced
- 6 chicken bouillon cubes
- 6 cups water
- 3 stalks broccoli - cut in bite-sized pieces
- 1 qart half/half or milk
- 1 to 1 1/2 cups flour
- 1/2 cup butter or margarine
- 1 to 2 cups cheddar cheese grated

### Directions {-}
In a large soup pan add potatoes, carrots, onions, celery, water and bouillon cubes. 
Bring to a boil, then simmer until vegetables are tender. Add the broccoli and simmer until tender. 

White Sauce:
In another pan add milk and melted butter. Add the flour, beat with wire whisk. 
Stir until it becomes thick. (Should be thick like paste). Add to vegetables. 
Stir until mixed well with vegetables. 
Add desired amount of cheese. If too thick add more milk.

---

## BUTTERMILK RANCH DRESSING WITH BIBB LETTUCE {-}

### Chef: Jennifer Gustin - by Barefoot Contessa {-}

### Ingredients {-}
- 3 scallions white and green parts - chopped
- 1/2 cup fresh basil leaves - lightly packed, chopped
- 2 tablespoons lemon juice - freshly squeezed
- 1 1/2 Tablespoons dijon mustard
- 1 tablespoon good olive oil
- 2 garlic cloves - chopped
- 2 1/2 teaspoons salt
- 1 teaspoon black pepper
- 1 cup good mayonnaise
- 1/2 cup Greek style yogurt
- 1/2 cup buttermilk - shaken

### Directions {-}
Place the scallions, basil, lemon juice, mustard, olive oil, garlic, salt,
And pepper in the bowl of a food processor fitted with the steel blade.
 Puree for 15 to 20 seconds to make a smooth mixture. Add the mayonnaise, 
Yogurt, and buttermilk and blend until smooth. Transfer the dressing to a 
container, cover, and refrigerate for 1 hour for the flavors to develop. 
Arrange the lettuce, tomatoes and onion artfully on salad plates and drizzle 
With the dressing. Sprinkle with salt and pepper and serve.

---

## CARROT CHOWDER {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 1 lb ground beef - browned & drained
- 1/2 teaspoon salt
- 1/2 cup celery - chopped
- 1/2 cup green pepper - diced
- 1/2 cup onion - diced
- Add all above to ground beef cover & simmer on low for 10 minutes.
- Add beef mixture listed above to the combined soup base listed below.
- 4 cups tomato juice
- 1 1/2 cups water
- 2 cans cream of celery soup
- 2 1/2 cups carrots - grated
- 1/2 teaspoons garlic powder
- 1/2 teaspoon salt
- 1/8 tsp [marjoram](https://en.wikipedia.org/wiki/Marjoram)

### Directions {-}
Bring all to a boil & simmer for 30 minutes

Serve by placing a slice or chopped Swiss or Monterey jack cheese in 
bowels and pour “hot” soup over the cheese.

Tastes much like a hearty tomato soup.

---

## FRITO CORN CHIP SALAD {-}

### Chef: Jennifer Gustin {-}

### Ingredients {-}
- 1/2 cup purple onion - diced
- 1/2 cup green bell pepper - diced
- 1/2 cup red bell pepper - diced
- 1/4 cup celery - optional - diced
- 1 1/2 cup cheddar cheese - shredded
- 1 (15 oz) can whole kernel corn
- 1 (10 oz) bag chili chese Fritos
- 3 tablespoons Ranch dressing
- 1/2 cup mayonnaise

### Directions {-}
In large bowl, mix all ingredients together except chips.
Chill for 2 hours. Add chips before serving.  Makes 10-12 servings

---

## ITALIAN MEATBALL SOUP {-}

### Chef: Patrica Blair {-}

### Ingredients {-}
- 3/4 lb ground Beef
- 3/4 lb pork sausage
- 2 eggs - beaten
- 1/2 cup parmesan cheese - binely grated
- 1/4 cup Italian bread crumbs
- 1 tablespoon garlic - finely chopped
- 1teaspoon [Italian Essence](https://www.emerils.com/121962/italian-essence)
- 1 teaspoon salt
- 2 pinches crushed red pepper
- Mix the above together and roll into small balls
- 2 tablespoons olive oil
- 1/2 cup onion - chopped
- 1/4 cup celery - chopped
- 2 tablespoons tomato paste
- 1 (14.5 oz) can crushed tomatoes
- 3 1/2 cup beef stock
- 3 cups water
- 1/2 cup ditalini or other small pasta
- 2 tablespoons fresh basil leaves - chopped

### Directions {-}
In a 4 1/2 quart soup pot add 1 tablespoons olive oil. Brown the meatballs 
(about 4 minutes). Transfer to a plate and set aside. Add onion, celery, stirring until vegetables
 are soft. Add tomato paste, crushed tomatoes, beef stock and water. 
 Return the meatballs to the soup and bring to a boil. Simmer for 30 minutes. 
Using a spoon, carefully skim any fat that has accumulated on the top of the soup and discard,
Add ditalini or other small pasta to the hot soup. 
Stir well and cook for 15 minutes or until the pasta is cooked through. 
Stir in basil and serve garnished with grated parmesan cheese.

---

## MANDARIN SALAD {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 1/2 cup sliced almonds
- 2 tablespoons sugar
- 1/2 head iceberg lettuce
- 1/2 head romaine lettuce
- 1 cup celery - chopped
- 2 whole green onions - sliced
- 11 oz can mandarin oranges

### Directions {-}
In a small pan over medium heat, heat almonds and sugar, stirring constantly 
Until almonds are coated and sugar is dissolved. Watch carefully as they will burn easily. 
Cool and store in airtight container. Mix lettuces, celery and onions. Just before 
serving, add almonds and oranges. Toss with dressing. (Excelent with sesame seed dressing).

---

## MEXICAN 2 BEAN CHILI {-}

### Chef: Jennifer Gustin {-}

### Ingredients {-}
- 1 can (15 oz) black beans - drained and rinsed
- 1 can (15 oz) pinto - drained and rinsed
- 1 can (8.5 oz) whole kenel corn - drained
- 1 can (16 oz) chunky salsa
- 1 can (8 oz) tomato sauce
- 3 cups shredded cooked chicken
- 2 - 3 garlic cloves - minced
- 2 tablespoons chili powder
- 1 teaspoon ground cumin
- 2 cups chicken broth

### Directions {-}
Drain and rinse beans and corn. Combine chicken broth, salsa, tomato sauce in large sauce pan. 
Add beans, corn chicken, garlic, chili powder and cumin. Bring to a boil, reduce heat 
And simmer 30 minutes to 1 hour. Serve.

---

## ORIENTAL SALAD {-}

### Chef: Patricia Blair {-}

### Ingredients {-}
- 1 pound cole slaw
- 1 cup scallions - chopped
- 1 cup sunflower seeds - shelled
- 1 cup almond slivers
- 2 package origional Ramon noodles
- DRESSING:
- 1 cup vegetable oil
- 1/3 cup vinegar
- 1/2 cup sugar
- seasoning packets from noodles

### Directions {-}
Toast almond slivers in a pan with a bit of oil.

Combine salad ingredients in a large bowel. In a separate bowel combine dressing 
Ingredients, whisk and chill. Add dressing to salad 2 minutes before serving

---

## SESAME SEED DRESSING {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 3/4 cup honey
- 1 teaspoon salt
- 1/2 teaspoon pepper (white is good)
- 1/2 cup oil
- 6 tablespoons vinegar
- 3 tablespoons sesame seeds - toasted

### Directions {-}
Mix all ingredients with wire whisk until thickened. Very good on salads made with green onion, 
thinly sliced celery, slivered almonds, red grapes and mandarin oranges.

---

## ZUPPA TOSCANA {-}

### Chef: Jennifer Gustin {-}

### Ingredients {-}
- 1 pound hot Itailian sausage
- 3 pounds potatoes - cubed with skin
- 1 large onion - chopped
- 2 cans chicken broth
- 3 cloves garlic - minced
- 2 cups kale - chopped
- 1 quart water
- 1 bag real bacon pieces
- 1 cup heavy cream
- salt and pepper to taste

### Directions {-}
Brown and drain sausage and set aside. In a large pot add water, broth, potatoes, onion, 
And garlic. Cook on medium heat until potatoes are don, add sausage, bacon pieces, 
Salt and pepper, and simmer for 10 minutes. Turn heat to low, add kale and heavy cream. 
Heat through and serve.

---

## MORE {-}

### Chef: Who {-}

### Ingredients {-}
- 2 T

### Directions {-}

---

# Vegetables & Side  Dishes {#Sides}

---

---

## SEA SALT SWEEET POTATOES {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 2 pounds (3 medium) yams - diced 3/4" cubes
- 1/2 teaspoon coarse sea salt
- 2 tablespoons vegetable oil
- 1/4 teaspoon pepper
- 1/4 cup maple syurp
- 1/4 cup pecan pieces - chopped coarse

### Directions {-}
Preheat oven to 425 deg and coat 9 x 13 baking pan with cooking spray. 
In a separate bowel, mix all ingredients together except pecans. 
Arrange mixture in backing pan. Bake for 25-30 minutes, stirring halfway through. 
Remove from oven sprinkle with pecans. Finish with a pinch of sea salt. Serves 4 to 6.

---

## BROCCOLI - CHEESE ALMONDINE {-}

### Chef: Lori Hilton {-}

### Ingredients {-}
- 2 to 3 cups broccoli florets and stem
- 2 tablespoon margarine
- 2 tablespoons onion - chopped
- 1/2 teaspoon salt
- 2 tablespoons rice flour
- 1 cup milk
- 1 cup cheddar cheese - grated
- 1 cup sliced almonds

### Directions {-}

Preheat oven to 350 deg. Cook the broccoli until barely tender. Drain and 
place it in a buttered 1 1/2 quart casserole dish. In a medium saucepan, melt 
the margarine and saute the onion until clear. Stir in the salt and flour. 
Add the milk slowly, stirring continually. Turn heat to medium and cook until 
Sauce has thickened. Add the cheese and stir until cheese melts. Spoon the cheese 
Sauce overt the broccoli. Top with almonds. Bake for 30 minutes. Makes 3 or 4 servngs.

---

## CAULIFLOWER "MASH" POTATOES {-}

### Chef: Lori Hilton {-}

### Ingredients {-}
- 1/2 Large head of cauliflower - broken florets
- 1/2 cup nonfat buttermilk
- 1/2 to 1/3 cup low-fat milk
- 1 pound Yukon gold potatoes - cut to 1/2 inch cubes
- 2 scallions - chopped
- 1 teaspoon salt
- 1/4 teaspoon pepper

### Directions {-}
Place the cauliflower in a steamer basket, set over boiling water, 
cover and steam for 15 minutes. Transfer to a food processor, add 
the buttermilk and ¼ cup of milk and puree until very smooth, about 2 
minutes. Place potatoes in a saucepan, add cold salted water to cover 
by about 2 inches, bring to a boil, reduce heat, and simmer until tender, 
about 15 minutes Drain, return to the saucepan, and heat over 
medium heat for 1 to 2 minutes to dry, mash with a potato masher. 
Add the cauliflower puree, ¼ cup milk, 1 tsp salt and ¼ tsp pepper. 
Stir to blend and heat over medium low heat, adding more milk as 
needed for a creamy consistency. Stir in butter and scallions and serve.

---

## "CROCK POT" GREEN CHILI BURRO SAUCE {-}

### Chef: Patricia Blair {-}

### Ingredients {-}
- 1 medium onion - diced
- 2 pounds stew meat - cut into chuncks
- 1 jar LaVictoria green taco sauce
- 1 jar LaVictoria green salsa
- 1 can green chilies - diced

### Directions {-}
Mix all ingredients in crock pot and simmer

---

## GARLIC MASHED POTATOES {-}

### Chef: Patricia Blair {-}

### Ingredients {-}
- 5 pounds potatoes
- 1/4 cup onion - grated
- 2 tablespoons butter
- 5 cloves garlic - minced
- 2 cups sour cream
- 1/4 cup butter - softened
- 2 teaspoons salt
- 1/2 teaspoon pepper

### Directions {-}
Peel potatoes and cut in large chunks. Cover with water and boil until tender. 
Drain water. Mash well and set aside. Microwave onion and the 2 tablespoons 
butter for 2 minutes. Add minced garlic to butter and onion. Microwave for 
1 minute, then add to potatoes. Stir in sour cream, the ¼ cup butter, salt, and pepper. 
Spoon into large casserole dish. Cover with foil, Bake at 325 degrees for 30 minutes. 
Makes 8 – 10 servings.

---

## GREEN BEAN CASSEROLE {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 2 cans green beans or 2 pkg. 9 oz frozen green beans
- 1 can of cream of mushroom soup
- 3/4 cup milk
- 1/8 teaspoon salt
- 1 1/3 cups Frenches Original French Fried Onions

### Directions {-}
In a 1 ½ quart casserole pan, mix all ingredients except 2/3 cups french fried onions. 
Bake for 30 minutes at 350 degrees or until hot. Stir, top with 2/3 cups onions. 
Bake 5 minutes or until onions ae golden. Serves 6

---

## GREEN BEANS WITH LEMON AND PINE NUTS {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 1 1/2 pounds green beans - fresh - trim and cut diagonally into 1/2" pieces
- 2 garlic cloves - finely minced
- 1/4 cup toasted pine nuts
- 2 tablespoons Italian parsley - fresh, finely chopped
- 1 large lemon - finely zest and juice
- 4 teaspoon extra-virgin olive oil
- salt and peper to taste

### Directions {-}
In a 4 quart sauce pan, boil in salted water, beans and minced garlic until just tender, about 5 minutes, drain. 
Transfer to a bowel and toss with nuts, parsley, zest, oil. Salt and pepper to taste. Makes 8 servings.

---

## MOM'S CURRIED RICE {-}

### Chef: Patricia Blair / Roberta Spencer {-}

### Ingredients {-}
- 1 cup white rice
- 6 tablespoons butter or margarine
- 1 cup onon - chopped
- 1 cup celery - chopped
- 1 teaspoon curry powder
- 1/8 teaspoon cayenne pepper - or to taste
- 2 cups chicken broth
- salt and pepper to taste

### Directions {-}
In a large frying pan, melt butter, onion, celery and sauté, stirring 
occasionally, until onion is translucent. Blend together the rice, curry 
powder, and cayenne pepper. Add to the onion mixture and stir while 
cooking until rice is coated, about 2 minutes. Pour in the broth. When it boils, 
cover the pan and reduce heat to low. Simmer until rice is tender and the broth 
is absorbed, 18 – 20 minutes. Add salt and pepper to taste.

---

## OLD-FASHIONED CREAMED CABBAGE {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 1 medium-sied head green cabbage
- 2 eggs, beaten
- 1 tablesoon butter or margarine - melted
- 3/4 teaspoon salt
- 1/4 teaspoon pepper
- 1/4 cup cream or nondairy liquid - undiluted
- 1/2 cup grated cheddar cheese, for topping - optional

### Directions {-}
Preheat oven to 400 degrees. Wash, core, and sherd the cabbage. In a saucepan
cook until tender then drain.
In a large bowl, combine the cabbage with the rest of the ingredients 
except the cheddar cheese. Pour mixture into a buttered 3 quart casserole 
or baking dish. Bake for about 15 minutes. Add the cheese topping, 
if desired, and return to oven for another 5 to 7 minutes. Makes 6 to 8 servings.

---

## QUINOA WITH PINE NUTS AND APRICOTS {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 1/4 cup dried apricots - chopped
- 1 bell pepper - chopped
- 1 bunch green onions - chopped
- 1 cup quinoa
- 1/2 cup pine nuts
- 1 teaspoon salt
- 1 tablespoon fresh lemon juice
- 1 teaspoon groound cumin
- 1/2 teaspoon ground corriander
- 2 tablespoons olive oil
- 
### Directions {-}
Bring 2 cups water to a boil in medium saucepan. Stir in quinoa, 
Cover, and simmer 10 minutes. Turn off heat, and let quinoa remain 
Covered 10 minutes more to absorb water. Transfer quinoa to bowl 
And fluff every few minutes until grain cools. Toast pine nuts in dry skillet 
Over medium heat, stirring until nuts are golden brown (3 minutes). 
Add pine nuts, salt, lemon juice, cumin, coriander, oil, apricots,
Green onions, and bell pepper to quinoa, and toss until coated.
Serve warm or chill and serve cold.

---

## RATATOUILLE {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 1 red onion
- 1 zucchini
- 1 yellow squash
- 1 bell pepper
- 10 button mushrooms
- 1 tablespoons garlic - diced
- Parsley - chopped
- extra-virgin olive oil
- salt and pepper to taste

### Directions {-}
Wash and chop the vegetables into 1/2 to 3/4 inch pieces for even cooking. 
Do not peel the vegetables. Be sure to dry the mushrooms well after washing. 
Wet mushrooms turn mushy when cooked. Place the dice vegetables in a large mixing bowl. 
Cover lightly with extra-virgin olive oil. Mix well to make sure all the pieces are covered in 
light oil, but avoid drenching. Too much oil leads to soggy vegetables. Season with salt, pepper, 
chopped parsley and diced garlic. Place a flat backing pan in a 500 degree oven. 
Allow the pan to roast in the oven until hot, about 5 minutes. Pour vegetables from the bowl onto 
the sizzling hot pan. The hot pan helps sear in the vegetables natural moisture. Bake at 500 degrees 
for 8 to 10 minutes, turning halfway through. The vegetables are done when the vegetables begin to turn grown on the edges. 
Ratatouille can be served hot as a vegetable entrée over rice or tossed with 
tomato sauce and served over pasta. It also can be served cold or at room temperature with bread or crackers.

---

## SAVORY SPINACH SQUARES {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 2 packages spinach - chopped
- 1 cup shredded American cheese
- 2 egggs
- 1/3 cup milk
- 1/4 cup butter - melted
- 1/2 onion - minced
- 2 tablespoons dry parsley flakes
- 1 teaspoon Worcestershire sauce
- 1/2 teaspoon salt
- 1/2 teaspoon thyme
- 1/2 teaspoon nutmeg
- 

### Directions {-}
Cook the spinach and drain well. Beat eggs, add combined milk, butter, 
onion, parsley flakes and Worcestershire sauce, salt, thyme and nutmeg 
and mix well. Combine spinach and cheese, add egg mixture and mix all well. 
Pour into a greased shallow pan 9 x 13. Bake at 325 degrees for 1 hour. 
Let cool a minute and cut into squares and serve. 12 servings

---

## MORE {-}

### Chef: Who {-}

### Ingredients {-}
- 2 T

### Directions {-}

---

# Main  Dishes {#Main}

---

---

## CREAMY SWISS CHICKEN BAKE {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- cooked rice
- 4 - 6 sliced chicken breast
- 6 - 8 slices swiss cheese
- 1/2 cup mayonnaise
- 1/2 cup sour cream
- 3/4 cup parmesan cheese - divided 1/2+1/4
- 1 teaspoon garlic powder
- 1/4 teaspoon salt
- 1/2 teaspoon pepper

### Directions {-}
Serve over cooked rice. Preheat oven to 375 degrees. In a bowl 
mix ingredients; mayonnaise, sour cream, parmesan cheese, salt, 
pepper and garlic powder. Spread over chicken and sprinkle with 1/2 cup 
parmesan cheese. Pat chicken dry and place in greased 9 x 13 pan. 
Spread mixture over chicken and sprinkle with parmesan cheese. 
Bake 1 hour at 375 deg. Serve over rice or serve alone.

---

## APRICOT CHIPOTLE CHICKEN {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 4 - 6 chicken breasts
- CHICKEN MARINADE
- 1 cup olice oil
- 2 tablespoons garic - minced
- 2 tablespoons paprika
- 1 teaspoon salt
- 1 teaspoon pepper
- APRICOT CHIPOTLE SAUCE
- 1 1/2 oz jar of apricot preserves
- 2 1/4 cup chicken broth
- 3 chipotle peppers

### Directions {-}
Trim chicken breast and put in marinade. Let marinate 2 - 24 hours. 
APRICOT CHIPOTLE SAUCE: Heat the apricot preserves until warm and 
add chicken broth and chipotle peppers. Blend with hand blender until peppers 
are integrated. Chipotle peppers will make the sauce spicier, so
 begin with one pepper and taste the sauce. Add more if needed. 
Pour over chicken, cover and bake at 350 degrees for 1 1/2 hours. 
May cook in crock pot on low for 6-8 hours. Delicious served over rice.

---

## BAKED CHICKEN AND RICE CASSEROLE {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 6 - 8 pieces of chicken - drumsticks or tighs
- 1 cup white rice - uncooked
- 2 cups chicken broth
- 1 package Lipton onion soup
- 1 small onion - chopped
- 1 teaspoon granulated bouillon - or 1 cube

### Directions {-}
Brown chicken in pan with enough oil to brown it. Remove chicken to a plate. 
Put 1 cup of rice in pan and add 2 cups chicken broth, 1 package Lipton onion soup, 
chopped onion and bullion. Put chicken on top of rice and cover with a lid. Simmer 
on low until rice and chicken are done. You can add extra liquid if it needs more.

---

## BAKED CHICKEN NUGGETS {-}

### Chef: Patricia Blair {-}

### Ingredients {-}
- 4 chicken breasts - boneless - skinless
- 1 1/2 cup Italian seasoned bread crumbs
- 2/3 cup grated parmesan cheese
- 1 1/4 teaspoon dried thyme
- 3 teaspoon dried basil
- 1 1/4 teaspoon salt
- 2/3 cup butter, melted

### Directions {-}
Preheat oven to 400 deg. Cut chicken breasts into 1 1/2 inch pieces. In a 
Medium bowl, mix together the bread crumb, cheese, salt, thyme and basil. 
Mix well. Put butter in a bowl for dipping. Dip chicken pieces into melted 
butter first, then coat with the breadcrumb mixture. Place well coated chicken 
pieces on a lightly greased cookie sheet in a single layer, and bake in 
the preheated oven for 20 minutes.

---

## BEEF AND BELL PEPPER SKILLET {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 1 pound greound beef
- 2 greem peppers - diced
- 1 cup onion - chopped
- 1 cup rice - uncooked
- 1 beef bullion cube - crushed
- 2 tablespoons soy sauce
- 2 1/2 cups water
- 1 small can of tomatoes - optional

### Directions {-}
Brown the beef in skillet, drain. Stir in green pepper, onion, rice, bullion water, 
and soy sauce. Bing to boil, reduce heat, cover and cook over low heat until 
liquid is absorbed, about 20 – 25 minutes. Also, this recipe is good with a small can of 
tomatoes. Drain tomatoes and fold in at the end of cooking. Heat and serve.

---

## BEEF AND BROCCOLI STIR-FRY {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 2 pounds top sirloin steaks - sliced 1/4" thick
- 1 medium onion - sliced thinly
- 2 medium heads broccoli
- 2 teaspoons ginger root - grated
- 1/2 cup sou sauce
- 2 tablespoons corn starch
- 1 tablespoon brown sugar - firm packed
- 1 clove Barlic - minced
- 1 teaspoon black pepper
- 2 tablespoons vegetable oil - divided

### Directions {-}

In small bowl combine soy sauce, brown sugar, garlic and pepper. 
Set aside. Heat 1 tablespoon vegetable oil in large skillet over 
medium high heat. Add beef, and stir-fry sauce, cook until almost 
cooked through, about 2 minutes. Transfer beef to a plate and cover 
to keep warm. Heat remaining oil in skillet, add onion and stir-fry sauce, 
cook for 5 minutes. Cut broccoli into florets (about 4 cups), add to 
skillet with soy sauce mixture, add ginger. Bring to boil and cook, 
stirring constantly, until sauce thickens, about 2 minutes. Serve with, 
rice and serve warm.

---

## BOUNTY RICE {-}

### Chef: Patricia Blair {-}

### Ingredients {-}
- 1 pound ground beef
- 1 can 14.5 oz diced tomato 
- 1 tablespoon salt
- 1/2 teaspoon oregano
- 1/2 teaspoon basil leaves
- 1/2 teaspoon garlic powder
- 3 cups cooked rice
- 4 cups shreded cabbage
- 1/2 cup sour cream
- 1 cup onion
- 1 cup green bell pepper
- 1 cup mozzarella cheese

### Directions {-}
Sauté ground beef until lightly browned. Stir in tomatoes, seasonings, rice, and cabbage. 
Cover and cook 10 - 15 minutes or until cabbage is tender crisp. Stir in sour cream, onions, 
and gree peppers. Heat through. Spoon into 3 quart casserole dish and sprinkle with cheese. 
Bake in oven at 350 degrees until cheese is melted

---

## CAFÉ RIO {-}

### Chef: Debbie Wescott {-}

### THE PORK {-}
- 1 pound pork tenterloin - up to 4-5 lbs
- 2 15 oz cans tomato sauce
- 1 1/2 cups brown sugar
- 1 can Coca-Cola
- 1 garlic clove - minced
- 1 /4 cilanro - diced

Place all ingredients in crock pot on medium for at least 4 hours. 
Shred cooked pork and put back in sauce. 
Drain excess sauce to desired consistency.

### THE CREAMY DRESSING {-}
- 1 packet Hidden Valley Ranch mix
- 8 oz salsa verde green salsa - LaVictoria brand
- 1/2 bunch cilantro with stems - diced
- 2 cloves garlic - minced
- 3/4 cup mayonnaise
- 3/4 cup sour cream
- 1/8 teaspoon hot sauce

Mix in blender. If needed, thin with buttermilk.

### THE RICE {-}
- 4 cups rice - uncooked
- 8 cups water
- 8 cubes chicken bouillon - or 8 teaspoons
- 2 teaspoons cumin
- 4 cloves garlic -minced
- 12 tablespoons butter - use 1/2 for healthier version
- 13 sprigs cilantro - chopped

Bring water with bouillon, cumin, and butter to boil. Add garlic, cilantro, 
and rice. Cook for about 20 minutes or until all water is absorbed. 
(I usually half the rice if I’m just cooking 1 pound of pork)

---

Great served with warm tortillas. Add beans if you wish.

---

## CHEESE MANICOTTE {-}

### Chef: Lori Hilton {-}

### Ingredients {-}
### THE SAUCE {-}
- 1 large onion - chopped
- 1 garlic clove - minced
- 2 tablespoons olive oil
- 12 ounces tomato paste
- 24 ounces water
- 2 tablespoons oregano - fresh
- 1 bay leaf
- 1 teaspoon salt
- 1/2 teaspoon pepper

### THE FILLING {-}
- 1 1/2 cup ricotta cheese - grated
- 6 eggs
- 4oz mozzarella cheese - grated
- 6oz parmesan cheese - grated
- 6 tablespoons butter
- 1 teaspoon salt
- 1/4 teaspoon pepper
- 2 tablespoons fresh basil - chopped

### Directions {-}
Preheat oven to 350°. To make the sauce, gently sauté the onion and garlic in olive oil 
in saucepan over medium heat until onion is translucent. Add the tomato paste and stir. 
Slowly add the water and stir. Add the seasonings and allow the sauce to simmer while preparing 
the manicotti and filling. FOR MANICOTTI: Bring a large pot of water to a boil, add olive oil, 
and drop in manicotti. Cook al dente, about 12 minutes. Drain and refresh under cold running water. 
FOR FILLING: Beat the ricotta with the eggs until combined in the large bowl with an electric mixer. 
Add the grated cheeses and softened butter, beat until everything is combined. Gently fill the 
cooked manicotti with the cheese mixture and arrange in two greased 9x13 pans. Cover the pasta 
in each pan with half the sauce. Bake for 35 minutes until the cheese is thoroughly melded and the sauce is bubbling.

---

## CHEESY BUCKWHEAT WITH GREEN CHILES {-}

### Chef: Jennifer Gustin {-}

### Ingredients {-}
- 4 cup cooked Cream of Buckwheat
- 1 cup onion - chopped
- 1/4 cup buter
- 1 cup low fat sour cream
- 1 cup cottage cheese
- 2 cup (8oz) sharp cheddar cheese - shredded
- 2 4oz cans green chilies - chopped
- 1 teaspoon salt
- 1/2 teaspoon pepper

### Directions {-}
Prepare Cream of Buckwheat, using either milk or water. Sauté onion in butter then combine 
with buckwheat, sour cream, salt and pepper. In 2 quart casserole dish layer buckwheat mixture, 
cheddar cheese and chilies and repeat layers. Bake uncovered at 375° for 30 minutes, 
or until bubbly and golden. Let stand about 10 minutes before serving. Serves 6

---

## CHICKEN ENCHILADA QUICHE {-}

### Chef: Jennifer Gustin {-}

### Ingredients {-}
- 1 pie crust
- 4 eggs
- 1 cup half-and-half or milk
- 1 can 12.5oz chunk chicken breast in water -drained = 1 1/2 cup
- 2 cup (8oz) monterey jack cheese - shredded
- 1 cup (4oz) cheddar cheese - shredded
- 1 cup Old El Paso Thick N' Chunky salsa
- 1 can (4.5oz) chopped green chilies
- 1/2 teaspoon salt
- Peper to taste
- 1 1/2 cup broken tortilla chips

### Directions {-}
Heat oven to 350°. In medium bowl beat eggs with wire whisk. Beat in half-and-half. Stir in chicken, 
both cheeses, salsa, green chilies and salt. Fold in broken tortilla chips. 
Pour into pie crust, sprinkle pepper over top of filling. Bake 55 – 64 minutes or until crust is lightly 
golden brown and knife inserted in center comes out clean. Let stand 10 minutes. Serve

---

## CHICKEN FAITA LETTUCE WRAPS {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}

### FOR FILLING: {-}
- 2 tablespoons olive oil
- 1 pound chicken - cut in bite-size pieces
- 1 tablespoon fajita spice
- 1 cupsliced onions
- 1 cup sliced peppers
- 2 cloves of garlic - chopped
- 1 tablespoon cilantro - chopped
- 1 teaspoon cumin

Heat oil in the pan over medium heat and add chicken and fajita spice. Cook for 5 minutes, and then 
add the rest of the filling ingredients. Simmer until chicken pieces are fully cooked.

### FOR LETTUCE WRAPS: {-}
- 8 iceburg lettuce leaves
- 1 cup sliced cabbage
- 2 avocados, sliced
- 2 cups salsa

### Directions {-}
Let each leaf from itself into a natural cup. Sprinkle slicked cabbage in the cups. 
Divide chicken filling among the cups and top each with avocado slices and salsa. 
Makes 4 servings of 2 fajitas each.

---

## COCKTAIL MEATBALLS {-}

### Chef: Amanda Tunison {-}

### Ingredients {-}
- 1 pound ground beef
- 1/2 cup dried bread crumbs
- 1/3 cup chopped onion
- 1/4 cup milk
- 1 egg
- 1 teaspoon Worcestershire sauce
- 1 teaspoon salt
- 1/8 teaspoon black pepper
- 3 tablespoons olive oil
- 12oz tomato based chili sauce
- 1 1/4 cups grape jelly

### Directions {-}
In large bowl, combine ground beef, bread crumbs, onion, milk, egg, Worcestershire sauce, salt and pepper. 
Mix together and shape into meatballs. In a large skillet, heat oil over medium eat. Add meatballs, 
in a large skillet, heat oil over medium heat. Add meatballs, and cook until browned, about 5-7 minutes                                                                        
Remove from skillet, and drain on paper towels. Add chili sauce and jelly to skillet, heat, stirring until 
jelly is melted. Return meatballs to skillet and stir until coated. Reduce heat to low. Simmer uncovered for 
30 minutes. Serve. Also delicious on riced            

---

## COLORFUL KIELBASA {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
-  1 can (10 3/4oz) condensed cream of celery soup
-  1 1/2 cups water
-  1 tablespoon butter or margarine
-  1 pond smoked keilbasa - cut into 1/2 inch pieces
-  3/4 cup long grain rice - uncooked
-  1 package (10oz) frozin peas
-  1 jar (4 1/2) sliced mushrooms - draind
-  1 cup (4oz) cheddar cheese - shreaded

### Directions {-}
In skillet, combine soup, water, and butter: bring to a boil. Add kielbasa and rice. Reduce heat; 
cover and simmer about 18 minutes or until rice is almost tender. Stir in peas and mushrooms. 
Cover and simmer 15 minutes or until rice is tender and peas are heated through. Sprinkle with cheese: 
cover and let stand until melted. Serves 4 - 6  

---

## CORNISH PASTIES {-}

### Chef: Rebecca Bright {-}

### Ingredients {-}
- 2 pounds beef or pork or combination of both
- 5 carrots - chopped
- 2 large onions - chopped
- 2 potatoes - peeled and chopped
- 1/2 rutabaga - chopped
- 1 - 2 tablespoons Worcestershire sauce
- 2 teaspoons salt
- 1/2 teaspoon pepper
- 6 prepared pie dough round or you cn make your favorite pastry rounds enough for six 10" pie rounds. Refer to recepie in "Curry Pasties".

### Directions {-}
Combine all ingredients, other than pastry, in large bowl. Set out pie crusts on a floured surface. Put 1 ½ cups of filling 
on half of the round. Moisten the edges and fold the unfilled half over the filling to enclose it. Pinch the edges together 
to seal them and crimp them decoratively with a fork. Transfer pasty to lightly greased baking sheet and brush with egg for 
a nice shiny glaze. Bake in a preheated 350° oven for 50-60 minutes until golden brown.

---

## CURRY PASTIES {-}

### Chef: Rebecca Bright {-}

### Ingredients {-}

### FOR THE FILLING {-}
- 1 pound ground beef
- 1 1/2 cups bread crumbs
- 1 large onion - chopped
- 1 cup chicken broth
- 1 teaspoon curry owder
- 1 tablespoon olive oil
- salt and pepper to taste

Sauté onions in 1 tablespoon olive oil. Add the three spices and cook until toasted and aromatic 
(only a couple minutes max) then add the meat, crumble and cook until brown. Add broth and then 
bread crumbs until the mixture sticks together but is not soggy. Add salt and pepper if needed.

### FOR THE PASTRY {-}
- 3 cups flour - sifted
- 1 1/2 cups cold butter - cut into 1/4 inch chunks
- 1 1/2 teaspoon salt
- 6 tablespons ice cold water
- Sour cream, chives, paprika - for topping

In a large bowl, combine flour, butter and salt. Blend ingredients until combined and add ice-water 
one tablespoon at a time to form a dough. Toss mixture until it forms a ball. Knead dough lightly 
against a smooth surface with heel of the hand to distribute evenly. Form into a ball, dust with flour. 
Wrap in wax paper and chill for 30 minutes.

### Directions {-}
On a well-floured surface roll out dough pie crust thin and cut into 6-8 inch rounds. 
Fill with approximately ¾ filling on one half of the round, fold over and seal edges with water 
and crimp using a fork. Transfer pasty to lightly greased baking sheet and brush with egg for a 
nice shiny glaze. Bake in a preheated 350° oven for 25-30 minutes until golden gown. 
Serve with sour cream and chives with a dash of paprika  

---

## DUPIAZZA (INDIAN CURRY DISH) {-}

### Chef: Rebecca Bright {-}

### Ingredients {-}
- 2 pounds chicken, beef or lamb - cubed
- 1 - 2 tablespoons olive oil
- 1 - 2 large yellow or sweet onions- chopped into large chunks
- 2 tablespoons garlic - minced
- 1 tablespoon ginger paste
- 1 - 2 grams masala - optional (1 gram=0.75oz or 1/4 teaspoon)
- 1 tablespoon turmeric
- 1 - 2 teaspoon cumin
- 1 tablespoon curry powder (I us half regular and half hot madras)
- 1 can 14oz or larger stewed fire roasted tomatoes
- 1 can chicken stock or chicken base and water
- 4 red chilies or 1/4 - 1/2 tablespoon red pepper
- 1 can coconut milk

### Directions {-}
Heat skillet with 1-2 Tablespoons olive oil on medium heat until it is hot, add onions, garlic, and ginger, 
and stir constantly until onions are about half cooked, then add all the spices except the chilies. 
Stir constantly for about 2 minutes until spices are heated and combined evenly over onions. 
Add cubed meat and stir until just browned on the outside. Add the tomatoes, stock and chilies, reduce heat, 
cover and simmer of 1/2 hour. Remove lid and raise heat and reduce liquid until it starts thickening, 
stirring about every 3-5 minutes (this may take another 1/2 hour or more). When it has started to thicken, 
add the coconut milk and stir until well blended. Reduce again until the consistency of gravy. 
Serve while hot over basmati rice and naan bread (Indian flat bread).

---

## EGG CASSEROLE {-}

### Chef: Patricia Blair {-}

### Ingredients {-}
- 1 large package shredded hash browns
- 2 cups milk
- 1 cup ham - diced
- 1 cup sasuage - cooked
- 6oz mozzarella cheese - shredded
- 6oz cheddar cheese - shredded
- 8-10 eggs - remove shell
- 1/4 cup onion - diced
- salt and pepper to taste

### Directions {-}
Layer potatoes, cheeses, and meats in 9x13 baking dish. Combine onion, eggs, 
milk, salt, and pepper; pour over mixture. Refrigerate overnight. Bake uncovered at 350° for 1 hour. 
Serve hot.

---

## FOIL DINNERS {-}

### Chef: Lori Hilton {-}

### Ingredients {-}
- 3-4 medium potatoes - peeled, 1/2" cubes
- 2-3 carrots - peeled and sliced
- 1 large onion - sliced or chopped
- 2-3 celery stalks - sliced
- 1 pound hamburger
- 1 package Lipton onion soup mix
- salt and pepper to taste

### Directions {-}
Cut up vegetables and mix together with onion soup mix. Form hamburger into 4 patties. 
Place each patty on its own aheet of aluminum foil, sized large enough to wrap and seal the individual 
serving  (shiny side up). If meat is lean add 1/2 teaspoon of oil or butter inside 
foil before sealing. Season hamburger with salt and pepper. Place vegetables on top of hamburger 
and season vegetables with salt and pepper. Seal foil by rolling the edges and cook in oven, 
on briquettes, or campfire coals. Use heavy duty foil or double layer over briquettes or campfire. 
Cooking time about 30 minutes. Serves 4. Serve with s'mores as dessert.

---

## GREEN CHILE CHICKEN CASSEROLE {-}

### Chef: Patricia Blair {-}

### Ingredients {-}
- 1 green bell pepper - chopped
- 3 ribs celery - chopped
- 3/4 cup chopped green onion
- 5 tablespoons butter
- 1 can chopped green chilies
- 1 1/2 ups rice - cooked
- 1 carton sour cream or Greek yogurt
- 3 boneless chicken breast - cooked and sliced

### Directions {-}
Preheat oven to 325°. Combine bell pepper, celery, green onions in skillet with butter and 
sauté for 5 minutes, transfer to bowl. Stir in green chilies, rice, sour cream, chicken broth, 
1/4 cup water, salt and pepper. Pour into sprayed 9x13 baking dish, cover and bake 40 minutes. 
Uncover and continue to bake for 10 minutes.

---

## GRITS, GREENS AND SAUSAGE {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 1 link (about 3oz) andouille sausage or other spicy cooked sausage - sliced
- 2 medium chile peppers (mild or hot) or half a bell pepper - chopped
- 4 ounces (about 4 cups) collard greens - chopped
- 1/2 cup low-fat (1%) milk
- 1/8 teaspoon salt
- 1/2 cup quick-cooking grits
- 1/2 tablespoon unsalted butter
- 1/2 teaspoon olive oil
- crushed red-pepper flakes to taste

### Directions {-}
Bring a large pot of water to a boil. Thinly slice sausage and peppers. Cook greens in boiling water until tender, 
about 8 minutes. Meanwhile, in a small pot, combine milk, I cup water and salt over medium heat. 
When it starts to bubbles, slowly stir in grits. Reduce heat to low and cook, stirring often, 
until grits are tender, about 5 minutes. Remove from heat and stir in butter. Cover and set aside, 
Drain collard greens and set aside. Return empty pot to medium heat. Add oil, sausage and peppers; 
cook about 2 minutes. Add cooked greens and toss until heated through. Dish grits into serving bowls 
and top with greens and sausage mixture. Season to taste with red-pepper flakes.

---

## HANBURGER FRY-PAN SUPPER {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 1 pound ground beef
- 1 medium onion - chopped
- 2 medium red potatoes - unpeeled, julienned (thin strips)
- 2 cups cabbage - shredded
- 2 cups celery - thinly sliced
- 1/2 cup water
- Salt and pepper to taste

### Directions {-}
In a large skillet, brown beef and onion; drain. Add remaining ingredients. Cover and simmer for 20 minutes 
or until vegetables are tender, stiring occasionally. Yield 6 servings.

---

## LEMON ASPARAGUS CHICKEN {-}

### Chef: Mike Sharp, Susan Sharp {-}

### Ingredients {-}
- 1 tablespoon vegetable oil
- 4 skinless chicken breast halves
- 1 can condensed cream of asparagus soup
- 1/4 cup milk
- 1 tablespoon lemon juice
- 1 teaspoon ground black pepper
- Lemon slices - for optional garnish

### Directions {-}
Heat oil in a ten inch skillet over medium high heat. Cook chicken for 10 minutes or until well browned 
on both sides. Stir in the soup, milk, lemon juice and black pepper in skillet. Heat to a boil, 
educe the heat to low. Cover and cook for 5 minutes or until chicken is cooked through. Garnish with lemon slices if desired.

---

## MEAT-LOAF {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 1 1/2 pounds ground beef
- 3 slices bread - torn into small pieces. (I use 3/4 cups oatmeal to make it gluten free)
- 1 egg
- 1 cup milk
- 1 small onion - chopped
- 1 tablespoon Worcestershire sauce
- 1 teaspoon salt
- 1/4 teaspoon pepper
- 1/2 teaspoon dry mustard
- 1/4 teaspoon rubbed sage
- 1/8 teaspoon garlic powder
- 1/2 cup ketchup - or chili sauce or barbecue sauce
- Omit the ketchup is doing mashed potato on top of meat-loaf

### Directions {-}
Mix all ingredients except catchup. Spread mixture in ungreased loaf pan or shape into loaf in ungreased 
rectangular pan. Bake uncovered in 350° oven until done (1-1 1/4 hours). Remove from pan, top with catchup. 
If desired cover with mashed potatoes and omit the ketchup. Make mashed potatoes and spread over 
meat loaf. Sprinkle 1/2 cup of cheddar cheese on top. Bake until cheese is melted, 2-4 minutes.

---

## ALFREDO SAUCE - (OLIVE GARDEN) {-}

### Chef: unknown {-}

### Easy Style {-}
- 1 stick of real butter
- 1 pint of heavy cream
- 2 tablespoons of cream cheese
- 3/4 cup parmesan cheese
- 1 teaspoon garlic powder

### Real Style (Large batch)
- 2 tablespoons garlic paste or minced garlic - browned
- 1 pound butter
- 2 quarts heavy whipping cream
- 8oz milk
- 1 pound grated parmesan cheese
- 4oz grated fontina cheese
- 1 teaspoon salt
- 1/2 teaspoon pepper

### Directions {-}
In a saucepan melt butter. When melted add garlic, cream cheese (and stir in other cheese). 
When soft, add heavy cream (and milk). Simmer for 15-20 minutes. Season with salt and pepper. 
Serve over pasta with chicken or shrimp.

---

## POLYNESIAN MEATBALLS {-}

### Chef: Jennifer Gustin {-}

### Ingredients {-}

### THE MEATBALLS {-}
- 1 pound ground beef
- 1/2 cup bread crumbs
- 1 small onio chopped
- 1 teaspoon cornstarch
- 1/2 teaspoon salt
- dash of Allspice
- 1 egg - beaten
- 3/4 cup ligt cream (in a pinch substitute milk)

Combine ingredients meat into walnut size balls and place in a baking.

### THE SAUCE {-}
- 1 bottle chili sauce
- 1 cup grape jelly

Combine chili sauce and grape jelly and heat until bubbly. Pour over meatballs and bake at 325° for 1 hour. 
Excellent over rice.

---

## SALISBURY STEAK WITH ONION GRAVY {-}

### Chef: Amanda Tunison {-}

### Ingredients {-}
- 1 can (10.5oz) condensed French onion soup - undiluted, divided
- 1 egg
- 1/2 cup dried bread crumbs
- 1/4 teaspoon salt
- dash of pepper
- 1 1/2 pounds ground beef
- 1/4 cup water
- 1/4 cup ketchup
- 1 teaspoon Worcestershire sauce
- 1/2 teaspoon mustard
- 1 tablesoon flour
- 6 cups hot cooked egg noodles 
- choped fresh parsley, optional

### Directions {-}
In a large bowl, beat egg. Stir in 1/3 cup of soup, bread crumbs, salt, pepper. Crumble beef over mixture; 
mix gently. Shape into six oval patties. In a skillet, brown patties over medium heat for 3-4 min on each side. 
Remove and set aside; drain. Add he water, ketchup, Worcestershire sauce, mustard and remaining soup, to skillet. 
Bring to a boil. Return patties to skillet. Reduce heat; cover and simmer for 15 minutes or until meat is 
no longer pink. Remove patties. Combine flour and cold water until smooth. Stir into pan. Bring to boil; 
cook and stir for 2 minutes or until thickened. Serve patties and gravy over noodles. Garnish with parsley if desired.

---

##  SALSA CON QUESO CHICKEN WITH ASPARAGUS {-}

### (easy cheesey chicken with asparagus) {-}

### Chef: Cody Gustin {-}

### Ingredients {-}
- 1 1/2 pounds chicken breast - bonless, skinless
- 2 teaspoons vegetable oil
- salt and pepper to taste
- 1 cp salsa con queso - mild or spicy, found in chip isle
- 1 pound pencil thn asparagus spears

### Directions {-}
Pound out chicken breast till roughly 3/4 inch thick. Heat oil in 12 inch skillet over medium heat. Sprinkle chicken 
generously with salt and pepper. Cook chicken through, about 4 minutes on each side. Meanwhile, snap ends of 
asparagus and rinse. Place asparagus in a 2 quart microwave safe casserole dish with a lid. Add 1/4 cup water. 
Cover and microwave 4 minutes or till crisp tender. Remove from th microwave and set aside. Put cheese in microwave 
about 2 minutes, stirring half way through. Arrange chicken breast on top of the asparagus, top with cheese sauce. 

---

##  SIMMERED CHINESE CHICKEN {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 1 whole cicken
- 1 tablespoon oil
- 1/3 cup brown sugar
- 1/2 cup water
- 1 tablespoon ketchup
- 1/4 cup apple juice
- 1/2 teaspoon red pepper
- 1/3 cup soy sauce
- 1 clove garlic - minced
- 1 green onion - sliced
- 2 teaspoons cornstarch
- 1 tablespoon water
- 2 teaspoons sesame seeds - toasted

### Directions {-}
Heat oil in Dutch oven, brown chicken on both sides. Mix soy sauce, brown sugar, water, catchup, 
red pepper, garlic and green onion. Pour mixture over chicken. Cover, simmer 35-45 minutes. 
Remove chicken to platter. Drain juices back to pan and skim fat. Blend together cornstarch and water, 
stir into sauce. Cook stirring till thickened. Spoon sauce over chicken and sprinkle with sesame seeds. 
Serve with sauce and rice.

---

## STUFFED BELL PEPPERS {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 6 large bell peppers  - green, red or yellow
- 1 pound ground beef
- 2 tablespoons onion - chopped
- 1 cup cooked rice
- 1 teaspoon salt
- 1/8 teasoon garlic salt
- 1 (15oz) tomato sauce
- 3/4 cup (3oz) shredded mozzarella cheese 

### Directions {-}
Cut thin slice from stem end of each pepper. Remove seeds and membranes; rinse peppers. Cook peppers 
5 minutes in enough boiling water to cover; drain. Stir in rice, salt garlic salt and 1 cup of the tomato sauce; 
heat through. Stuff each pepper with beef mixture; stand up-right in ungreased 8"x8" baking dish. 
Pour remaining sauce over peppers. Cover dish and bake in 350° oven for 45 minutes. Uncover; bake 15 minutes longer. 
Sprinkle with cheese. 6 servings; 290 calories per serving.

---

##  SUPER NACHOS {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 1 pound ground beef
- 1 large onion - chopped
- 2 small cans refried beans
- 1 can (4oz) diced green chilies
- 2-3 cups shredded cheddar cheese
- 1 cup salsa
- tortilla chips - 
- garnish if desired, sour cream, ripe olives, lettuce

### Directions {-}
Grown and drain the hamburger and onion. Salt to taste. In 9”x13” pan spread refried beans, 
top with meat mixture. Sprinkle diced chilies over meat. Cover with cheese and drizzle with salsa. 
Bake uncovered at 350° for 25-30 minutes. Remove from oven and garnish with green onions, ripe olives 
and sor cream. Serve with chips and lettuce.

---

##  SHEPHERDS PIE TDF (To Die For) {-}

### Chef: Rebecca Bright {-}

### Ingredients {-}
- 1 pound ground beef
- 1 pound ground elk, venison or other lean game meat
- 5 carrots - chopped into small pieces
- 1 large oion - chopped
- 1-2 tablespoons garlic - minced
- 1 1/2 cups beef stock
- 1 tablespoon Worcestershire sauce
- salt and pepper to taste
- 6 cups mashed potatoes
- 1/2-1 tablespoons maramite - melted into 1/4 cup VERRY HOT water
- 2 cups sharp cheddar cheese

### Directions {-}
Sauté onion and garlic in 1 tablespoon olive oil over medium high heat, add ground meat, 
crumble and cook until browned. Add carrot, stock marmite, Worcestershire, salt and pepper. 
Cover and simmer for 15 minutes. Pour this mix into a large deep baking dish or disposable aluminum tray. 
Spread the mashed potatoes on top of the meat, top with cheese and bake in preheated oven 375° 
for 30 minutes or until cheese is bubbly and gets slightly browned spots.

---

##  TOAD IN THE HOLE (YORKSHIRE PUDDING) {-}

### Chef: Rebecca Bright {-}

### Ingredients {-}
- 1 1/2 cups all purpose flour
- salt - about a teaspoon
- pepper - a pinch, freshly ground black pepper
- 3 eggs - beaten
- 1 1/2 cups milk
- 2 tablespoons butter- melted
- 1 tablespoon vegetable oil
- 1 pound (give or take) of sausage links - I like to use the Little Smokies but you can use full size and cut them into chunks. Use the fully cooked sausage unless you pre-cook them.

### Directions {-}
(1)	In a large bowl, whisk together the flour with the salt and a pinch of pepper. Make a well in the center of the flour. 
Pour in the eggs, milk, and melted butter into the well and whisk into the flour until smooth. Cover and let stand 30 minutes.
(2)	Coat the bottom and sides of an 8”x12” or 9”x9” (or we like to do individual ones in a cupcake pan) casserole dish 
with vegetable oil (we use olive oil). Place a rack in the bottom third of the oven. Put the empty dish on the rack. 
Preheat the oven with the dish in it to 425°F.
(3)	When an is hot add your sausages to the bottom, for individuals put one sausage into each cupcake well and put back into 
the oven until VERY hot, Smoking HOT is ideal. 
(4)	Remove tray and quickly add your batter to the tray/wells and return to oven, cook until they rise nicely and are 
golden brown, about 25 minutes for a pan and a bit less for the individuals.

---

##  WESCOTT SWEET SPAGHETTI SAUCE {-}

### Chef: Debbie Wescott {-}

### Ingredients {-}
- 1 can (14.5oz) diced tomato - Add any veggies you would like
- 1 1/2 cups sugar - reduce if you'd like
- 3/4 teaspoon yellow mustard
- 1 1/2 teaspoon Italian seasonings - more for stronger flavor
- 1/2 onion - chopped
- 1 tomato - diced
- 3 cans (28oz) crushed tomato
- 1-2 tablspoons chopped garlic - jar or fresh
- 2 tablespoons olive oil

### Directions {-}
Heat the olive oil in a larger Dutch oven size pot.  Sauté garlic and onion until clear, add tomato and other 
veggies and sauté for a few minutes.  Pour in the crushed tomato, add all other ingredients and mix well.  
Heat just to a bubbling boil, cover and reduce heat to low (2-3) on my stove. 
Let cook for about 3 hours stirring occasionally.  If you are doing meatballs… you may cook them right 
in the sauce for the last 45 minutes or so of the 3 hours cooking time.  For meatballs I combine pork 
sausage with ground beef and salt and pepper about 1-1 1/2 lbs. all together.  Form into smaller meatballs 
and drop directly into the sauce.  1-2 inch meatballs seem to absorb the flavor better, but do not over cook 
them or they are not as tender.  Italian sausage is also great in the sauce too.  This, I slice and cook 
in a separate pan before adding to the sauce.

---

##  WOW ASIAN LETTUCE WRAPS {-}

### Chef: Rebecca Bright {-}

### Ingredients {-}
- 1 pound ground turkey
- 2 tablespoons FRESH ginger - minced
- 1/2 cup onion - diced
- 1 cup veggie blend (found in "This and That" secton "HEALTHY FOOD TIPS" IN this cookbook)
- 1/2 cup millet - cooked
- 1/2 cup quinoa - cooked
- Yoshidas or other teriyaki sauce to taste
- chili sauce to taste
- iceberg lettuce or butterhead lettuce
- scallions for garnish

### Directions {-}
Cook turkey then add garlic, ginger, onions, veggie blend. This will cook quickly, you want veggies to be tender. 
Add the grains and teriyaki sauce. Serve in lettuce with a dash or more of chili sauce.

---

##  WOW LASAGNA {-}

### Chef: Rebecca Bright {-}

### Ingredients {-}
- 1 bound Italian sausage - spicy for more flavor
- 1 cup dry quinoa
- 1 large jar spaghetti sauce - or make yor own
- 1 cup veggie blend (found in "This and That" secton "HEALTHY FOOD TIPS" IN this cookbook)
- 1 can great northeren beans
- 1 box lasagna noodles - or make your own, it is even better
- mozzarella cheese
- 1/4 cup parmesan cheese (the real stuff)
- 16oz cottage cheese
- 2 eggs - beaten
- 2 tablespoons parsley
- 2 tablespoons garlic powder
- 1/2 teaspoon salt 

### Directions {-}
Brown the sausage with dry quinoa in a pan.  Once browned add 1 cup water, 
cover and simmer for 10 minutes.  Once quinoa is cooked add 1 cup veggie blend, and great northern beans. 
In a separate bowl mix: cottage cheese, eggs beaten, parsley, Parmesan cheese, garlic powder, salt.  
In pan, layer sauce, noodles (cooked), cheese mix, meat, repeating layers until all ingredients are used.  
Cover top with mozzarella and Parmesan cheese.  Bake at 375° until cheese is bubbly and turning golden.

---

##  SLOW COOKER CHILI {-}

### Chef: uknown {-}

### Ingredients {-}
- 1 pound ground beef
- 3/4 cup onion - diced
- 3/4 cup celery - diced
- 3/4 cup green bell pepper - diced
- 2 cloves garlic - minced
- 2 cans (10.75oz) tomato puree
- 1 can (15oz) kidney beans - with liquid
- 1 can (15oz) kidney beans - drined
- 1 can (15oz) cannellni beans - with liquid
- 1/2 tablespoon chili powder
- 1/2 teaspoon dried parsley
- 1 teaspoon salt
- 3/4 teaspoon dried basil
- 3/4 teaspoon dried oregano
- 1/4 teaspoon ground black pepper
- 1/8 teaspoon hot pepper sauce

### Directions {-}
1)	Place the beef in a skillet over medium heat, and cook until evenly brown.  Drain grease.
2)	Place the beef in a slow cooker, and mix in onion, celery, green bell pepper, garlic, 
tomato puree kidney beans, and cannellini beans.  Season with chili powder, parsley, 
salt, basil, oregano, black pepper, and hot pepper sauce.
3)	Cover, and cook 8 hours on low.

---

##  MORE {-}

### Chef: who {-}

### Ingredients {-}
- 

### Directions {-}


---

# Breads and Rolls {#Breads}

---

---

##  CINNAMON ROLLS {-}

### Can Ue Used For Rolls or Doughnuts {-}

### Chef: Rosetta Spencer {-}

### Ingredients {-}
- 2 packages yeast
- 1/2 cup warm water - 98 degrees, no warmer
- 1 cup warm water
- 1/2 cup butter -softened
- 3 eggs
- 5 cups flour - sifted
- 2 teaspoons salt
- 1/2 cup sugar - use more if making doughnuts
- cinnamon
- Brown sugar and more butter

### Directions {-}
Dissolve 2 pkgs. Yeast in 1/2 cup warm water (over 100° will kill the yeast).  Mix in 1/2 cup sugar 1/2 cup of butter, 
and 1 cup warm water, mix well.  Add 3 eggs, mix.  Add 5 cups flour and 2 teaspoons salt, mix.  
Let rise, punch down.  Let rise second time, punch down and divide in half.  Roll out, spread with butter 
then spread with a 1/8" thick layer of brown sugar .  Sprinkle with cinnamon, then roll up.  Cut about 1 1/2 inch pieces and put end way in 
pepared pan, spaced looslely allowing room to raise.  Prepare the baking pan with a heavy layer of butter then cover with brown sugar about 1/4” thick. 
Let the rolls rise.  Bake in about 325° oven until brown, about 20 minutes.  Frost while warm with thin frosting.

---

##  CRUMPETS-GLUTEN FREE {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 1 1/2 cups gluten free flour mix
- 1 1/2 teaspooons baking powder
- 1 teaspoon xanthan gum
- 1/2 teaspoon gum
- 1 1/2 tablespoons sugar - divided
- 1 cup lukewarm water
- 1 tablespoon dry yeast granules
- 1 egg - room temperature
- 1 teaspoon dough enhancer - or 1/2 teaspoon vinegar
- 3 tablespoons margarine or butter - melted

### Directions {-}
Mix together the flour, baking powder, xanthan gum, salt, and egg replacer ( if used ).  Set aside.  Add 1 teaspoon or the sugar to the water and stir in the yeast.  Set aside.  Grease 6 English muffin rings and place them on a greased baking sheet.  I use small Corning ware dishes for these.  In a mixing bowl, blend together, using a mixer at low speed, the remaining sugar, egg, margarine, dough enhancer, and yeast water.  Beat in half the flour mixture.  With a spoon, stir in the remaining flour and beat until smooth.  Pour batter into the prepared rings or dishes.  Cover and let rise in a warm place until the batter doubles, 40 – 45 minutes for regular yeast; 20 – 25 minutes for rapid rise.  Preheat oven to 375°.  Bake for 18 to 20 minutes until browned lightly and pulled slightly away from the rings.  Makes 6 crumpets.

---

##  DROP SCONES-GLUTEN FREE {-}
### and Pancakes {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 1 cup gluten free flour
- 1/3 teasoon xanthan gum
- 1 egg - beaten
- 1/2 cup milk or non dairy liquid
- 2 1/2 tablespoons sugar
- 1 teaspoon dark corn syrup
- 2 tablespoons butter or margarine - melted
- 2 teaspoons baking powder
- 1/4 teaspoon salt

### Directions {-}
In a medium bowl, blend the flour and xanthan gum.  Add the egg and then beat into the flour mixture, gradually adding the milk.  Beat to the consistency of thick cream.  Add the sugar, syrup, butter, baking powder, and salt.  Beat well.  Drop the batter onto a medium-hot Teflon or lightly greased griddle by the tablespoon to make scones 2 ½ inches in diameter.  Cook as for pancakes, but since these are thicker, they will need to be on the heat longer, since these are thicker, they will  need to be on the heat longer, so don’t have the griddle extra hot, or you will have doughy centers.  Serve hot.  Split to fill with butter and jam, sausage, or cheese.  Makes 5 or 6 scones.  I use this recipe to make Dad’s pancakes.  I use about double the amount of milk to thin it enough for pancakes.

---

##  FRUIT BRAN MUFFINS {-}

### Chef: Jennifer Gustin {-}

### Ingredients {-}
- 2 cups raisn bran
- 1 egg
- 1 (11oz) can mandarin oranges lightly chopped (save the juice)
- 1 banana - mashed
- 1/4 cup butter - melted
- prune juice (see directions for amount)
- 1 cup flour
- 1/3 cup brown sugar
- 1/2 tablespoon baking soda
- 2 tablespoons baking powdeer
- 1 tablespoon cinnamon
- 1/2 cup raisins
- 1/2 cup cup nuts (optional)

### Directions {-}
In a medium bowl, mix Raisin Bran, egg, oranges, banana, and melted butter.  Add the prune juice to the mandarin oranges to make 1 cup.  Mix the 1 cup juice into the Raisin Bran mixture.  Let stand 5 minutes.  In a medium bowl, mix flour, brown sugar, baking soda, baking powder, cinnamon, raisins, and nuts together until combined.  Add the mixture to the Raisin Bran mix.  Pour mixture into lined cupcake molds and bake for 25 minutes at 375°.

---

##  NAVAJO FRYBREAD {-}

### Chef: Susan Sharp {-}

### Ingredients {-}
- 4 cups flour
- 1 tablespoon baking powder
- 1 teaspoon salt
- 2 tablespoons powdered milk
- 1 1/2 cup water

### Directions {-}
Put all dry ingredients in a large bowl.  Using your hands slowly mix in water.  Mix into a soft not sticky dough.  Preheat shortening in a fry pan 1/2 inch to 1 inch of oil.  Using your hands form a small amount of dough into a circle 6 to 8 inches in diameter or use a rolling pin.  Place in hot oil.  Turn when underside is golden brown.

---

##  SPICY CORN MUFFINS-GLUTEN FREE {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 1 cup gluten free flour mix
- 1/2 teaspoon xanathan gum
- 3/4 cup yellow cornmeal
- 1 1/2 teaspoon baking powder
- 2 teaspoon egg replacer (optional)
- 1 teaspoon salt
- 1 teaspoon baking soda
- 1/4 teaspoon cayenne pepper
- 2/3 cup liquid egg substitute
- 1 cup yogurt
- 1/4 cup vegetable oil
- 1/2 cup green onions - finely sliced

### Directions {-}
Heat oven to 425°.  Spray 12 2 1/2” muffin cups with vegetable oil spray.  In a medium bowl, blend flour mix, xanthan gum, cornmeal, baking powder, Egg Replacer (if used), salt, baking soda, and cayenne pepper.  In a large bowl, beat the egg substitute slightly with a wire whisk.  Add the yogurt and oil and whisk.  With spoon, stir in the flour mix until just blended.  Stir in the green onions.  Spoon into prepared muffin cups.  Bake 15 minutes or until tester comes out clean.  Serve hot from the oven or cool to serve later.  Makes 12 2 1/2'” muffins.

---

##  MORE {-}

### Chef: Who {-}

### Ingredients {-}
- 

### Directions {-}


---

# Desserts {#Deserts}

---

---

##  BLUEBERRY CRISP {-}

### Chef: Patricia Blair {-}

### Blueberry Mixture {-}
- 6 cups blueberries - rinsed and lightly dried
- 1 tablesoon cornstarch
- 1/4 cup sugar
- pinch of salt

Combine blueberries, cornstarch, sugar and a pinch of salt together in bowl. Place in a greased 2 quart baking dish. 

### Topping Mixtue {-}
- 1/2 cup al-purpose flour
- 1/2 cup quick cooking oats
- 1/4 cup packed light brown sugar
- 1/4 cup sugar
- 1/2teaspoon ground cinnamon
- 1/4 teaspoon ground nutmeg
- 3/4 cups pecans - chopped
- 1/2 stick butter - unsalted, cubed, room temperature
- Whipped cream for topping - optional

Preheat oven to 375°.  Combine flour, oats, brown and white sugar, cinnamon, nutmeg, and pecans in a bowl. Add butter and pinch into chunks. Mix until it looks crumbly. Place evenly over the bluberries in the bakng pan. Bake for 40 minutes. Serve with whipped cream or ice cream.

---

##  CRANBERRY-APPLE CRISP {-}

### Chef: Roberta Spencer {-}

### Fruit Filling {-}
- 4-5 cups apples - peeled, cored and sliced
- 1 cup cranberries - fresh or frozen
- 2/3 cups sugar
- 2 teaspoons cinnamon
- 1 teaspoon allspice

Tumble together the apples, cranberries, sugar, cinnamon, and allspice. Pout into an 8” square glass baking dish with 2” sides. Microwave on high for 4 to 5 minutes, stirring several times. Set aside, it is ready to receive the crumble topping.

### Crumble Topping {-}
- 1 cup almonds - sliced then crushed
- 2/3 cup dark brown sugar
- 1/3 cup white rice flour
- 1/4 cup (1/2 stick) butter - melted
- Whipping cream, frozen yogurt, or ice cream -optional topping

Preheat oven to 350°. Blend together the almonds, sugar, flour and butter. Crumble this mixture over the top of the fruit filling. Bake for 25 to 30 minutes, or until the top is slightly brown and the juice oozes up around the edges. Remove and let set 10 minutes to finish cooking. Serve hot or cold in glass desert dishes topped, if desired, with the whipping cream or ice cream. Makes 6 to 8 servings.

---

##  CREAM CHEESE BARS {-}

### Chef: Patricia Blair {-}

### Ingredients {-}
- 1 (18.5oz) package yellow cake mix - you can use any flavor mix
- 1/2 cup butter - melted
- 3 eggs - beaten, seperated
- 1 (8oz) package cream chese - softened
- 3 1/2 cups poowder sugar

### Directions {-}

Preheat oven to 350°. Grease and flour a 15”x10” sheet pan. Mix together cake mix, butter, and 1 egg. Press mixture into pan. In a small bowl mix together cream cheese, 2 eggs, and powder sugar. Pour mixture on top of cake mixture. Bake for 15 minutes. Reduce temperature to 300° and bake for 30-35 minutes. Cool and cut into squares.

---

##  CARROT AND PLUM CAKE - GLUTEN FREE {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 2 cups brown rice flour
- 1 scant teaspoon xanthan gum
- 1 cup sugar
- 2 teaspoons bakiing soda
- 2 teaspoons baking powder
- 1/2 teaspoon salt
- 1 tablespoon mpkin pie spice
- 1 seaspoon dried lemon zest
- 1 16oz can plums with some juice, or four 2 1/2oz jars baby prunes plus enouth water to make 1 1/4 cups
- 3/4 cup liquid egg substitute
- 3 tablespoons vegetable oil
- 3 cups gratted carrots

### Directions {-}
Heat oven to 350°. Spray a Bundt pan with vegetable oil spray and dust with rice flour. In a large mixing bowl, combine flour, xanthan gum, sugar, baking soda, baking powder, salt, spice, and lemon zest. Set aside. Drain the plums, reserving the juice; pit them and purée them in the food processor, adding enough of the reserved juice to make 1 ¼ cups. Combine the purée, egg substitute, and oil, beating to mix well. Stir into the flour mixture along with the grated carrots. Pour batter into prepared pan and bake for 1 our and 10 minutes or until a tester comes out clean. Cool in pan 10 minutes before turning out. If desired, while still warm, drizzle on a thin icing of confectioners’ sugar mixed with fruit juice. Note: I have always used the baby prunes and it works out well. I have also used a 9x13 pan as Dad likes this better than a Bundt pam. I made this cake for Lori and Beau’s wedding to take on their honeymoon. They really liked it.

---

##  LEMON BARS {-}

### Chef: Patricia Blair / Lion House Recipes {-}

### Ingredients {-}
- 1/2 cup butter or margarine - softened
- 1/4 cup powdere sugar
- 1 cup flour
- 2 egggs
- 1 cup sugar
- 2 tablespoons flour
- 2 tablespoons lemon juice
- lemon zest of 1/2 lemon

### Directions {-}
CRUST: Cream butter and sugar; add 1 cup flour. Spread in an 8x8 pan and bake at 325° for 15-20 minutes. While crust is baking prepare next layer. FILLING: Beat eggs slightly and add sugar, flour, lemon juice and zest. Mix well and our over hot crust after it comes from oven. Now bake for 15 -20 minutes at 325°. Remove from oven and sprinkle and sifted powder sugar. Cool slightly before cutting.

---

##  LEMON POKE CAKE {-}

### Chef: Roberta Spencer {-}

### CAKE {-}
- 1 box Duncan Hines Lemon Supreme cake mix
- 3/4 cup oil
- 3/4 cup water
- 4 eggs
- 2 teaspoon lemon extract
- 1 small box lemon jello - dry powwder

Mix all ingredients and ut in greased and floured 9x13 pan and bake at 350° for 35-40 minutes. Prick top crust with a fork, put on topping.

### Topping {-}
- 1 1/2 cups  powdered sugar
- 6 tablespoons lemon juice

Mix powdered sugar and lemon juice. Prick top crust of cake with a fork. Pour on topping.

---

##  NUTELLA BROWNIES {-}

### Chef: Jennifer Gustin {-}

### Ingredients {-}
- 3/4 cup flour
- 1/4 teaspoon salt
- 1/3 cup butter - softened to room temperature
- 1 cup sugar
- 2 eggs - large
- 1 teaspoon vanilla extract
- 1 cup tutella

### Directions {-}
Preheat oven to 350°. In a small bowl combine flour and salt and set aside. Using an electric mixer blend butter until light and fluffy. Mix in sugar, eggs, vanilla and mix well followed by Nutella and stir until mixture is creamy. Stir in flour mixture. Pour into greased 11x7 or 8” rectangular baking pan and bake for 27-32 minutes. Cool pan on wire rack.

---

##  WHIPPED ORANGE JELL-0 {-}

### Chef: Jennifer Gustin {-}

### Ingredients {-}
- 1 package orange Jell-O - Large
- 1 Package vanilla pudding mix - the cook variety, not instant
- 1 150z can Mandarian oranges - juice reserved
- 2 cups liquid- include orange juice and add enough water to make 2 cups liquid
- 1 cup heavy whipping cream

### Directions {-}
Combine Jell-O, pudding and liquid in a sauce pan. Stir and cook on medium heat until mixture turns clear and boils for 1 minute. Pour into bowl and chill until it thickens. Whip the cream to stiff peaks. Fold the oranges into the Jell-O mixture then fold in the whipped cream. Chill.

---

##  PIGGY PUDDING {-}

### Chef: Debbie Wescott {-}

### Crust / Layer 1 {-}
- 1 cup flour
- 1 stick butter - softened
- 1 cup chopped pecans

CRUST/1st layer – Mix ingredients together. Press into 9x13 pan and bake for 20 minutes on 350°.

### Layer 2 {-}
- 8oz cream cheese - softened
- 1 cup powdered sugar
- 1 cup Cool-Whip

Mix and spread over the crust/1st layer

### Layer 3 {-}
- 1 small package instant vanilla pudding
- 1 small package instant chocolate pudding
- 2 cups milk
- 1 Hershey chocolate bar

Beat together until thick. Spread on top of 2nd layer. Spread remaining cool whip over the top. Grate chocolate bar over top. Refrigerate until served.

---

##  PUMPKIN PATCH {-}

### Chef: Patricia Blair {-}

### Ingredients {-}
- 6 eggs
- 1 large can pmpkin
- 1/2teaspoon cloves
- 1 1/2 teaspoons ginger
- 1 1/2 teaspoon cinamon
- 3/4 teaspoon salt
- 1 1/2 cups sugar
- 1 13oz can evaporated milk plus add milk to make 2 cups
- 1 yellow cake mix
- 1 cube butter or margarine - melted

### Directions {-}
Beat eggs. Add pumpkin and mix together. Add cloves, ginger, cinnamon, salt, sugar, and evaporated milk. Pour into 9x13 pan. Sprinkle yellow cake mi on top (dry). Drizzle 1 cube melted butter over cake mix. Bake 325° for 60 minutes

---

##  PUMPKIN ROLL {-}

### Chef: Lori Hilton {-}

### Ingredients {-}
- 1/4 cup powdered sugar (to sprinkle on towel)
- 3/4 cup all-prpose flour
- 1/2 teaspoon baking powder
- 1/2 easpoon ground cinnamon
- 1/2 teaspoon baking soda
- 1/2 teaspoon ground cloves
- 1/4 teaspoon salt
- 3 large eggs
- 1 cup granulated sugar
- 2/3 cup LIBBYS 100% Pure Pumpkin
- 1 cup walnuts (optional) - chopped
- 1 8oz package cream cheese - softened
- 1 cup powdered sugar - sifted
- 6 tablespoons butter or margarine - softened
- 1 teaspoon vanilla extract
- 1/4 cup powdered sugar - optonal

### Directions {-}

Preheat oven to 375°. Grease 15x10 jelly-roll pan; line with wax paper. Grease and flour paper. Sprinkle towel with powdered sugar. Combine flour, baking powder, baking soda, cinnamon, cloves and salt in small bowl. Beat eggs and sugar in large mixer bowl until thick. Beat in pumpkin. Stir in flour mixture. Spread evenly into prepared pan. Sprinkle with nuts. Bake for 13-15 minutes or until top of cake springs back when touched. Immediately loosen and turn cake onto prepared towel. Carefully peel off paper. Roll up cake and towel together, starting with narrow end. Cool on wire rack. Beat cream cheese, powdered sugar, butter and vanilla extract in small mixer bowl until smooth. Carefully unroll cake; remove towel. Spread cream cheese mixture over cake. Re-roll cake. Wrap in plastic wrap and refrigerate at least on hour. Sprinkle with powdered sugar before serving.

---

##  LIBBY FAMOUS PUMPKIN PIE {-}

### Chef: Found on the Libby's can {-}

### Ingredients {-}
- 2 eggs - beaten
- 1 15oz can Libby Pumpkin
- 3/4 cup sugar
- 1/2 teaspooon salt
- 1 teaspoon cinnamon
- 1/2 teaspoon ginger
- 1/4 teaspoon cloves
- 1 can evaporated milk
- 1 pie shell - unbaked
- whipped cream or CoolWhip - topping optional

### Directions {-}
Mix sugar, salt cinnamon, ginger and cloves in small b owl. Beat eggs in large bowl. Stir in pumpkin and sugar-spice mixture. Gradually stir in evaporated milk. Bake in preheated 425° oven for 15 minutes, reduce heat to 350° and bake 40-50 minutes, or until knife comes out clean. Top with whipped cream. Serves 1 to 8 people.

---

## PUMPKIN CAKE - GLUTEN FREE {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 1 1/2 to 1 3/4 cups organic sugar
- 3 eggs
- 1 can pumpkin (15oz or roughly 2 cups)
- 1/2 cup butter - melted, or 1/2 cup coconut oil, or 1/4 cup butter and 12 tablespoons flax meal
- 2 cups gluten free flour - included in directions below
- 2 teaspoons aluminum free baking powder
- 1 teaspoon baking soda
- 1/2 - 3/4 teaspoons sea salt
- 1 - 1 1/2 teaspoons cinnamon
- 1/2 - 1 cups nuts - chopped, optional 

Mix all ingredients and bake in a 9x13 pan at 350° for about 25-30 minutes or till firm. Top with cream cheese frosting if desired.

### Cream cheese Frosting {-}
- 3oz cream cheese - softened
- 6 tablespoons butter
- 1 teaspoon vanilla
- 1 tablespoon milk
- 2-3 cups organic powdered sugar

Combine all ingredients together in a mixer. Frost cake.

### Gluten Free All Purpose Flour {-}
- 2 cups rice flour
- 2/3 cups potato starch or corn starch
- 1/3 cup tapioca flour
- 1 teaspoon xanthan gum

Mix all ingredients together very well.

---

##  TRIFLE {-}

### Chef: Rebecca Bright {-}

### Directions {-}
One of the most important parts of Trifle is the BOWL you will make it in. Choose a deep clear glass bowl so that you can see all the beautiful colorful layers. Select at least 2 contrasting Jell-O colors; three layers would be better if you have room. Make sure you make it the night before the dinner event, or start early in the morning so that it has ample time to setup. Individual servings can be prepared in clear cups in the same manor.

### 1st Layer Fruit and Jell-o {-}
- 1 can fruit coctail or mixed fruit - no juice
- 1 layer of brightly colored Jell-O

Drain juice from the fruit cocktail, pour into large clear glass bowl. Prepare a package of Jell-O as directed on the Jell-O package. Refrigerate and let set completely before adding your next layer.

### 2nd Layer Sponge Cake and Jell-O {-}
- 1 sponge cake or Lady Finger cookies
- 1 layer of brightly colored Jell-O - probably 2 packages of Jell-O

After the 1st layer is firm, add sponge cake or Lady Fingers on top of 1st layer then cover with contrasting color Jell-O. Refrigerate and let set completely before adding your next layer.

### 3rd Layer Jell-O (Optional) but recomended {-}
- 1 layer of brightly colored Jell-O liquid mixture - probably 2 packages.  Refrigerate and let set completely before adding your next layer.

### 4th Layer Custard {-}
- double batch of [Bird's Custard](https://en.wikipedia.org/wiki/Bird%27s_Custard)
- whipped cream topping
- candy sprinkles

Prepare custard as directed on the package. Layer mixture over the trifle. Refrigerate and let set completely. Serve with whipped cream topping. Add candy sprinkles for a dash of color.

---

##  MORE {-}

### Chef: who {-}

### Ingredients {-}
- 

### Directions {-}


---

##  MORE {-}

### Chef: who {-}

### Ingredients {-}
- 

### Directions {-}


---

# Cookies and Candy {#Cookies}

---

---

##  GRANDMAS BEST CHOCOLATE CHIP COOKIES {-}

### Chef: Roberta Spencer/allrecipes {-}

### Ingredients {-}
- 1 cup butter - softened
- 1 cup white sugar
- 1 cup packed brown sugar
- 2 eggs
- 2 teaspoons vanilla extract
- 1 teaspoon vakng soda
- 2 teaspoons hot water
- 1/2 teaspoon salt
- 3 cups all-purpose flour
- 2 cups semisweet chocolate chips
- 1 cup chopped walnuts - optional

### Directions {-}
1.	Preheat oven to 350°.
2.	Ream together the butter, white sugar and brown sugar until smooth. Beat eggs one at a time, then, stir in the vanilla. Dissolve baking soda in hot water. Add to batter along with salt. Stir in, chocolate chips and nuts. Drop by large spoonful’s onto ungreased pan.
3.	Bake for about 10 minutes in the preheated oven, or until edges are nicely browned.

---

##  SERIOUSLY SOFT MOLASSES COOKIES {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 2 1/4 cups all-prpose flour - spoon & leveled
- 1 1/2 teaspoons baking soda
- 2 teaspoons grond ginger
- 1 1/4 teaspoons cinnamon
- 1/4 teaspoon grond cloves
- 1/4 teaspoon nutmeg
- 1/4 teaspoon salt
- 3/4 cup unsalted butter - softened to room temperature
- 1/2 cup packed brown sugar - light or dark
- 1/4 cup granulated sugar
- 1/4 cup unsulphured or dark molasses
- 1 large egg - at room temperature
- 2 teaspoons pure vanilla extract

### Directions {-}
1.	Whisk the flour, baking soda, ginger, cinnamon, cloves, nutmeg, and salt together until combined. Set aside.
2.	In a large bowl using a hand-held or stand mixer fitted with a paddle attachment, beat the butter and both sugars together on high speed until creamy and combined, about 2 minutes. Add the molasses and beat until combined. Then add the egg and vanilla extract and beat (until it screams) or until combined, about 1 minute. Scrape down the sides and bottom of the bowl as needed.
3.	On low speed, slowly mix the dry ingredients into the wet ingredients until combined. The cookie dough will be slightly sticky. Cover dough tightly with aluminum foil or plastic wrap and chill for 1 hour and up to 2-3 days.
4.	Preheat oven to °. Line two large baking sheets with parchment paper or silicone baking mats. (Always recommended for cookies). Set aside.
5.	Remove cookie dough from the refrigerator. If the cookie dough chilled longer than 2 hours, let it sit at room temperature for at least 30 minutes. The cookies may not spread in the oven if the dough it that cold. Roll cookie dough, 1 tablespoon each, into balls. Roll each in granulated sugar and arrange 3 inches apart on the baking sheets. Bake for 11-12 minutes or until edges appear set. If the tops aren’t appearing cracked, remove the baking sheet from the oven and gently bang it on the counter 2-3 times. This will help those warm cookies spread out and crack on top. Return to the oven for 1 additional minute.
6.	Remove from the oven and allow cookies to cool on the baking sheet for 5 minutes before transferring to a wire rack to cool completely.
7.	Cookies will say fresh covered at room temperature for 1 week.

---

##  EASY NO-BAKE COOKIES {-}

### Chef: Debbie Wescott {-}

### Ingredients {-}
- 4oz butter or margarine
- 1/2 cup milk
- 2 cups sugar
- 3/4 cup semi-sweet chocolate chips
- 3 cups oatmeal - regular or fast cooking
- 1 teaspoon vanilla
- 4 tablespoons peanut butter

### Directions {-}
Place chocolate chips, peanut butter, oats and vanilla in a  large bowl. Combine margarine, milk and sugar in saucepan and bring to a boil for about 1 minute. Combine hot mixture with dry mixture, stir well. Drop each cookie by spoonfuls on wax paper lined cookie sheet and cool or refrigerate.

---

##  EASY PUMPKIN SPICE COOKIES {-}

### Chef: Debbie Wescott {-}

### Ingredients {-}
- 2 boxs spice cake mix
- 1 29oz can of packed pumpkin (pie mix)
- 1 package chocolate chips or/and walnuts, raisins, or pecans
- cream cheese frosting - optinal

### Directions {-}
Mix cake mix and pumpkin together until well blended. Add chocolate chips and the balance of the ingredients. Drop by rounded spoonfuls onto cookie sheet. Bake 13-15 minutes at 350° Cool before removing rom cookie sheet. Frost with cream cheese frosting. Medium scoop makes about 6 dozen.

---

##  CANDIED CITRUS PEEL {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 4 or 5 oranges - or lemons may be combined
- 12 cups cold water
- 2 cups sugar
- 1/2 cup honey
- 3/4 cups boiing water
- 6oz semisweet - or whte choclate drops (more if needed)

### Directions {-}
Wash fruit and “score” (peel into quarters). Remove sections of peels and cut into uniform strips, about 3/8 “ wide to make about 3 cups of peels. In large saucepan, bring peels and 6 cups water to a boil; boil for 10 minutes. Drain, rinse peels and repeat process with 6 cups fresh water. In large saucepan, bring 1 1/2 cups sugar, 1/2 cup honey and 1 3/4 cups water to a boil for 1 minute. Add drained peels and simmer 40-45 minutes, stirring frequently to prevent sticking. Drain peels well for about 10 minutes. Place remaining sugar in a small bowl. Toss drained peels with sugar until well coated. Spread peels on wax paper to dry. Peels must be very dry for chocolate to adhere. In the top of a double boiler or in microwave, melt chocolate, stirring occasionally. Dip two-thirds of each peel strip into melted chocolate and place on waxed paper. After chocolate has set, store dipped peels in an airtight container in cool, dry, place. Makes 60 to 80 candied peels.

---

##  CRAZY CORN {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 1 1/2 cups white sugar
- 1 cup margarine
- 1/2 cup [light Karo corn syrup](https://en.wikipedia.org/wiki/Corn_syrup)
- 1 teaspoon vanilla
- 4 quarts popped popcorn
- 1 cup your favorite nuts - optional, I use pecan halves

### Directions {-}
Combine sugar, margarine, corn syrup and vanilla in a saucepan. Place over medium heat and mix to boil, stirring constantly until mixture begins to turn light caramel color. Remove from heat, add 1 cup nuts if desired. Pour hot mixture over 4 quarts popped popcorn, quickly stir until all popcorn is covered. Spread out on table or surface that can take heat, and let cool, when cool break apart and eat as a snack.

---

## CARMEL CORN - MICROWAVE {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 14 cups popped popcorn
- 1 cup brown sugar
- 1/2 cup margarine or butter
- 1/4 cup [light Karo corn syrup](https://en.wikipedia.org/wiki/Corn_syrup)
- 1/2 teaspoon baking soda

### Directions {-}
Put popped popcorn in large brown paper bag. Microwave 1 cup brown sugar, 1/2 cup margarine, 1/4 cup Karo syrup in a large bowl on high for 3 minutes. Stir, microwave 2 additional minutes on high. Make sure it is rolling boiling. Stir in ½ teaspoon baking soda until mixed well and fluffy. Pour over popcorn in brown bag. Roll bag closed. Microwave 1 1/2 minutes on high. Stir and shake. Microwave 1 minute on high, shake. Microwave 1 minute on high. Yum, yum!

---

##  BEST CARAMEL CORN EVER! {-}

### Chef:Patricia Blair {-}

### Ingredients {-}
- 7 quarts (28 cups) plain popped popcorn
- 2 cups dry roasted peanuts - optional
- 2 cups brown sugar - packed
- 1/2 cup light corn syrup
- 1 teaspoon salt
- 1 cup butter
- 1/2 teaspoon baking sodah
- 1 teaspoon vanilla

### Directions {-}
Place the popped popcorn into two shallow greased baking pans. Yo may use roasting pan, jelly roll pans or disposable roasting pans. Add the peanuts to the popped corn if using. Set aside. Preheat the oven to 250°. Combine the brown sugar, corn syrup, butter and salt in a saucepan. Bring to a boil over medium heat, stirring enough to blend. Once the mixture begins to boil, foil for 5 minutes while stirring constantly. Remove from the heat, and stir in the baking soda and vanilla. The mixture will be light and foamy. Immediately pour over the popcorn in the pans, and stir to coat. Don’t worry too much at this point about getting all of the corn coated. Bake for 1 hour, removing the pans, and giving them each a good stir every 15 minutes. Line the counter top with waxed paper. Dump the corn out onto the waxed paper and separate the pieces. Allow to cool completely, then store in airtight containers or resalable bags.

---
##  MAGIC COOKIE BARS {-}

### Chef: Susan Sharp {-}

### Ingredients {-}
- 1 1/2 cups of corn flake crumbs
- 1 cup chocolate chips
- 3 tablespoons sugar
- 1 1/3 cups flaked coconut
- 1/2 cup butter - melted
- 1 cup walnuts - pieces
- 1 cup condensed milk

### Directions {-}
In a bowl mix thoroughly, corn flake crumbs, sugar and butter. Press mixture evenly and firmly into bottom of 9x13 pan to form crust. Scatter chocolate chips over crust. Spread coconut over chocolate chips. Sprinkle nuts over coconut. Pour milk over nuts. Bake at 350° about 25 minutes or until lightly browned around edges. Cool, cut into bars. Makes 54 bars 2x1 inch.

---

##  MELT-IN-MOUTH CARAMELS {-}

### Chef: Patricia Blair {-}

### Ingredients {-}
- 1 cup butter
- 1 pound brown sugar
- dash of salt
- 1 cup light corn syrup\
- 1 can (14oz) sweetened can milk
- 1 teaspoon vanilla

### Directions {-}
Melt butter in saucepan. Add brown sugar and salt. Stir until combined. While cooking over medium heat, stir in corn syrup and mix well. Gradually add milk stirring constantly. Heat until candy reaches firm ball state 245° on candy thermometer. About 12-15 minutes. Remove from heat, stir in vanilla. Pour into a buttered square 9” pam. Cool and cut into squares. This recipe makes about 2 1/2 pounds. I precut wax paper and wrap the caramels up in them.

---

##  MONSTER COOKIES - GLUTEN FREE {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 6 eggs
- 2 cups packed brown sugar
- 1/2 tablespoon vanilla
- 4 teaspoons [light Karo corn syrup](https://en.wikipedia.org/wiki/Corn_syrup)
- 1 cup butter - softened
- 1 1/2 pounds peanut butter
- 9 cups oatmeal - blend to powder (optional) in a blender to make it "flour like"
- May add these variations: 1 pound chocolate chips, or M&M plain, 1 pound bag of shredded coconut

### Directions {-}
Mix all ingredients together. Drop buy large tablespoons or small ice-cream scoop, platen; bake 12 minutes at 350°. Don’t overbake – they turn hard on an ungreased cookie sheet. Let set on cookie sheet 5-10 minutes to cool before removing off the pan.

---

##  PEANUT BUTTER COOKIES {-}

### Chef: Patricia Blair {-}

### Ingredients {-}
- 1 1/4 cup flour
- 3/4 teaspoons baking soda
- 1/4 teaspoon salt
- 1/2 cup peanut butter
- 1/2 cup white sugar
- 1/2 cup brown sugar - packed
- 1/2 cup butter -room temperature
- 1/2 cup sugar (to roll doug in)

### Directions {-}
Preheat oven to 375°. Sift together flour, baking soda, and salt. Set aside. In medium bowl cream together butter, peanut butter, ½ cup white sugar, and brown sugar until smooth. Beat in egg then stir in vanilla. Gradually blend in sifted ingredients. Shape dough into 1 inch balls and roll in sugar.

---

##  QUICK'N EASY ENGLISH TOFFEE {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 1 pound butter
- 2 tablespoons [light Karo corn syrup](https://en.wikipedia.org/wiki/Corn_syrup)
- 6 tablespoons water
- 2 cups sugar
- 12oz package semi-sweet chocolate chips
- 1/2 pound sliced almonds or chopped walnuts
- 1 8oz Hershey's sweet chocolate bar

### Directions {-}
Let butter melt in a heavy kettle. (You can substitute butter for margarine. I have always used butter.)Then add Karo syrup, water, and sugar. Stir until sugar is dissolved on medium hear. When it starts to boil, stir occasionally while you do the following: Select a cookie sheet with sides. Butter the sheet, then spread chocolate chips evenly in the pan. Cover with nuts. Stir candy from bottom of pan frequently. When it begins to turn tan, put in dandy thermometer. You have to stir more often or it will burn. When mixture reaches 280°, pour thinly and evenly over chips and nuts. This has to be done quickly or you will not be able to spread the candy evenly across the pan. Cover all areas (a measuring cup with a pour edge works well or best to pour directly from the saucepan. Some minor spreading can be done to even out. As soon as candy is poured and spread, to it with chunks of the chocolate bar which will melt and then can be spread across the entire surface. When slightly cool, sprinkle 1 cup of finely chopped walnuts on the surface. Let cool. Set preferably overnight, then break in chunks and store in quart jars. This is better when aged 2 to 3 days. It will keep for a good amount of time. This candy has become a family tradition at Christmas time. I usually make three or more batches depending on how much I plan to give as gifts.

---

##  SPICED NUTS (5 MINUTES) {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 1 cup sugar
- 1/3 cup evaporated milk
- 1/1 teaspoon cinnamon
- 1 pound nuts - walnuts, pecans, or almonds

### Directions {-}
Bring to boil 1 cup sugar, 1/3 cup evaporated milk, 1/4 teaspoon cinnamon. Boil about 2 minutes. Remove from heat and stir in 1 pound of nuts, Lay on waked paper to cool.

---

##  SUGAR COOKIES {-}

### Chef: Patricia Blair {-}

### Ingredients {-}
- 1 1/2 cups butter - softened
- 3 cups white sugar
- 4 eggs
- 2 teaspoons vanilla extract
- 2 cups all purpose flour
- 2 teaspoons baking powder
- 1 teaspoon salt

### Directions {-}
In a large bowl, cream together butter and sugar until smooth. Beat in eggs and vanilla. Stir in the flour, baking powder and salt. Cover, and chill dough for at least one hour (or overnightr). Preheat oven to 400°. Roll out dough on floured surface 1/4 to 3/8 inch thick. Cut into shapes with any cookie cutter. Place cookies 1 inch apart on ungreased cookie sheets. Bake 6 to 8 minutes in preheated oven. Cool completely. TIP: Roll cookie dough out on parchment paper and cut out shapes with cookie cutter. Remove dough around cut outs and transfer parchment paper ont cookie sheet. This way you don’t ruin the cookies by peeling them off the counter and you can reuse the parchment paper for your next batch.

---

##  THICK AND CHEWY CHOCOLATE CHIP COOKIES {-}

### Chef: Jennifer Gustin {-}

### Ingredients {-}
- 2 1/8 cups all purpose flour (10 1/2oz)
- 1/2 teaspoon salt
- 1/2 teaspoon baking soda
- 12 tablespoons (1 1/2 sticks) unsalted butter - melted and cooled slightly
- 1 cup brown sugar (7oz)
- 1/2 cup granulated sugar (3 1/2oz)
- 1 large egg
- 1 large egg yoke
- 2 teaspoons vanilla extract
- 1 - 2 cups chocolate chips or chocolate chunks

### Directions {-}
1.	Heat oven to 325 degrees. Adjust oven racks to upper and lower-middle positions. Mx flour, salt and baking soda together in medium bowl; set aside. 
2.	Ether by hand or with electric mixer, mix butter and sugars until thoroughly blended.. Mix in egg, yolk, and vanilla. Add dry ingredients; mix until just combined. Stir in chips.
3.	Form scan ¼ cup dough into ball. Place formed dough onto one of two parchment paper-lined 14x20 lipless cookie sheets, about nine dough balls per sheet. Smaller cookie sheets can be used, but fewer cookies can be baked at on tome and baking time may need to be adjusted. (Dough can be refrigerated up to 2 days or frozen up to 1 month-shaped or not.)
4.	Bake, reversing cookie sheets’ positions halfway through baking, until cookies are light golden brown and outer edges start to harden yet centers are still soft and puffy, 15 to 18 minutes (start checking at 13 minutes). (Frozen dough requires an extra 1 to 2 minutes baking time.) Cool cookies on cookie sheets, Serve or store in airtight container.

---

##  WHITE CHOCOLATE CHIP BUTTERSCOTCH COOKIES {-}

### Chef: Patricia Blair {-}

### Ingredients {-}
- 2 1/2 cups flour
- 1 teaspoon baking soda
- 1/4 teaspoon salt
- 2 sticks unsalted butter - softened
- 1 1/2 cups dark brown sugar
- 2 eggs
- 1 tablespoon light molasses 
- 2 teaspoons vanilla extract
- 1 cup chopped pecans, toasted - optional
- 3/4 cup butterscotch chips
- 3/4 cup white chocolate chips                                      

### Directions {-}
Heat oven to 300°. In a medium bowl, combine the flour, baking soda and salt. In a large bowl with an electric mixer, cream the butter and sugar. Add the eggs, molasses, and vanilla. Blend well. Add the flour mixture and mix to blend. Stir in the pecans, butterscotch chips and white chocolate chips. Do not overmix. Drop the cookie dough by rounded tablespoons 2 inches apart onto an ungreased cookie sheet. Bake for 1-20 minutes or until set. Transfer to wire racks to cool.

---

##  MORE {-}

### Chef: who {-}

### Ingredients {-}
- 

### Directions {-}


---

##  MORE {-}

### Chef: who {-}

### Ingredients {-}
- 

### Directions {-}


---

##  MORE {-}

### Chef: who {-}

### Ingredients {-}
- 

### Directions {-}


---

##  MORE {-}

### Chef: who {-}

### Ingredients {-}
- 

### Directions {-}


---

---

# This and That {#ThisThat}

---

---

##  GRAVY {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 2 cups of broth with pan dripping - add water if less than 2 cups
- 2 tablespoons cornstarch
- Salt and pepper to taste

### Directions {-}
Pour broth and drippings into a saucepan and heat on low. Mix cornstarch with some cold water and add t drippings and broth stirring while adding. If it is not thick enough you may add more cornstarch mixed with water.

---

 ##  BBQ Rub {-}

### Chef: Alvin Spencer {-}

### Ingredients {-}
- 4oz garlic powder
- 4oz garlic salt
- 4oz lemon pepper
- 3 oz cayanne pepper
- 8oz black pepper

### Directions {-}
Mix all ingredients together. Store in a shaker bottle. Spread generously on meat and cook, cook, cook!

---

##  BARBECUE SAUCE {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- 1 can 6oz tomato sauce
- 1/4 cup dark Karo corn syrup
- 1/2 cup apple cider vinegar
- 1/2 cup catsup (please use Heinz for best flavor)
- 1 cup brown sugar
- 1/2 cup water
- Corn Starch - as needed to thicken
- Onion - diced - optional

### Directions {-}
Put all ingredients in a saucepan and bring to a boil. Boil for about 3 minutes then thicken with corn starch and water mixture to desired consistency; much thicker for chicken, also add one chopped onion to sauce for chicken. Excellent with pork roast, spareribs, and chicken. With pork roast and spareribs, brown the meat in 350° oven until well browned, then cover with sauce, baste occasionally. Cook for at least one hour. For chicken just arrange chicken pieces in baking dish. Pour thick sauce over, it will thin as chicken cooks. Bake at 350° until done, about 1 1/2 hours. Suggest lining pan with foil as this is a good pan sticker. It is also yummy!

---

##  CARAMEL FROSTING {-}

### Chef: Patricia Blair {-}

### Ingredients {-}
- 1/2 cup butter or stick margarine
- 1 cup packed brown sugar
- 1/4 cup milk
- 2 cups powdered sugar

### Directions {-}
Melt butter in 2 quart saucepan over medium heat. Stir in brown sugar. Heat to boiling, stir constantly; reduce heat to low. Boil and stir 2 minutes. Stir in bilk. Heat to boiling; remove from heat. Cool to lukewarm, about 30 minutes. Gradually stir in powdered sugar. Place saucepan of frosting in bowl of cold water. Beat with spoon until smooth and spreadable. If frosting becomes too stiff, stir in additional milk, 1 teaspoon at a time, or heat over low heat, stirring constantly. Frosts 9x13 inch cake, or fill and frosts an 8 or 9 inch layer cake.

---

##  KALE CHIPS {-}

### Chef: Patricia Blair {-}

### Ingredients {-}
- 1 head kale - washed and thoroughly dried
- 2 tablespoons olive oil
- sea salt - for sprinkling

### Directions {-}
Preheat oven to 275°. Remove the ribs from the kale and cut into 1 ½ inch pieces. Lay on baking sheet and toss with olive oil and salt. Bake until crisp, turning the leaves halfway through, about 20 minutes. Serve as finger food. It’s yummy to sprinkle vinegar on the kale also.

---
##  CINNAMON APPLESAUCE ORNAMENTS {-}

### Chef: Roberta Sepncer {-}

### Ingredients {-}
- 6 tablespoons warm applesauce (not chunky)
- 10 tablespoons cinnamon

### Directions {-}
Mix to form ball. Roll out 1/4 to 1/8 inch thick on countertop, sprinkle with cinnamon. Cut out your favorite shapes. Poke hole at the top with a straw. Place on cookie racks on a dehydrator tray (so air can circulate around dough). The can be place on dehydrator until hard or bake on lowest oven setting 5 to 6 hours or until hardened. Can be tole painted. Gingerbread men make adorable gifts.

---

##  DRIED APPLE WREATH {-}

### Chef: Roberta Spencer {-}

### Ingredients {-}
- Apples
- Lemon juice

### Directions {-}
Slice apples length wise every 1/4 in. Dip in lemon juice and place on cookie rack or dehydrator tray (air needs to circulate around apple). Dry in dehydrator o in oven on lowest oven temperature until dried. Blue on wooden embroidery hoop and attach a pretty Christmas bow.

---

##  PLAYDOUGH {-}

### Chef: Patricia Blair {-}

### Ingredients {-}
- 3 cups flour
- 1 1/2 cups salt
- 3 cups water
- 2 tablespoons vegetable oil
- 1 tablespoon of tartar
- Food coloring or unsweetened Kool-Aid packet

### Directions {-}
In a large saucepan, mix all ingredients together cooking on medium low heat. Stir frequently until the dough pulls away from the side of the pan and becomes too thick to stir (about 10-15 minutes). Remove from heat and let cool until it can be handled. Place on counter and knead several times until it becomes smooth. Store in an air-tight container.

---
##  MORE {-}

### Chef: who {-}

### Ingredients {-}
- 

### Directions {-}


---

