# Biography {- #bio}

Jack W. Hilton has been facilitating the financing, acquisition, and development of real estate projects 
in the Arizona market since 1976. 
His credentials include 45 years of experience in the local real estate market, 
where he has witnessed and participated in Arizona's dramatic growth.

Mr. Hilton has been active as an owner of mortgage companies, 
a real estate brokerage and management company, 
a licensed broker dealer company, 
as well as construction and development companies.
His infatuation with real estate industry started 
when he purchased his first small apartment complex at the age of 19. 
Shortly thereafter, he built his first spec home, 
which led to the construction and management of numerous small apartment buildings during the early to mid-1980s.

Mr. Hilton became a real estate lender in the early 1980s to assist, in part, 
the planning and acquiring, and financing for his own projects. 
As family members began to develop their own real estate projects and needed access to financing, 
Mr. Hilton decided to obtain his Mortgage Brokers License. 
He received his first Mortgage Brokers License on October 1, 1983, 
which led to bigger and greater involvement in this exciting field.

Some of Mr. Hilton's accomplishments include:

- Funding more than $1 billion of private money loans since 1990.
- Being instrumental in turning a local bank under regulatory enforcement in 1996 into a profitable financial institution. Rocky Mountain Bank went from a single branch location to seven, including five branches that were located inside Super Walmart locations. Under his leadership the bank grew from $20 million in assets to $130 million during an eight-year period. Mr. Hilton was a director and chairman of the bank. He transformed the bank from a privately owned institution into a public bank listed on Nasdaq’s OTC Pink bulletin board.
- Being instrumental in formation of Metro Phoenix Bank in 2006 where he currently serves as the chairman and a director of the Bank.
- Serving previously as the president, director, treasurer, and secretary of numerous HOA associations.
- Previously owning and operating a licensed broker dealer company specializing in private equity offerings.
- Raising millions of dollars in the syndication of mortgage loans and real estate projects.
- Developing numerous subdivisions through various stages of planning—from the initial design and preliminary platting process, to acquiring subdivisions that already had preliminary or final plats—and then completing the actual onsite development.

Mr. Hilton is currently the chairman and president of Hilton Financial Corporation, 
acting as the designated broker for Hilton Realty Corporation, and chairman and president of Phoenix MGP, Inc., 
which serves as the general partner and/or manager of numerous entities. 
He is a past director and president of the Arizona Private Lenders Association.


To contact Jack Hilton with questions or comments, you can email him at <jack@hiltoncorp.com>. 
