--- 
title: "Be The Bank"
author: "Jack W Hilton"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook: default
  bookdown::pdf_book:
    keep_tex: yes
    latex_engine: xelatex
    toc_unnumbered: no
    toc_appendix: yes
documentclass: book
link-citations: yes
github-repo: hiltonfinancialcorp/hiltonfinancialcorp.github.io
description: "You Are the Bank!"
indent: true
header-includes:
  - \usepackage{wrapfig}
  - \usepackage{indentfirst}
---


# Disclaimer {- #disclaimer}

The information in this book is not intended to serve as legal or professional advice. It is provided with the understanding that the author and the publisher are not engaged in rendering legal, accounting, or other professional service.

The reader should not rely on the material in this text. If legal, professional, or expert assistance is required, the services of a competent professional should be sought. 

© Copyright 2020 by Jack Hilton 

All rights reserved.

---

|   Jack Hilton, President
|   Hilton Financial Corporation 
|   11024 N 28th Drive, Suite 170 
|   Phoenix, AZ 85029-4329

---

# Acknowledgements {- #acknowledgements}

For this book the following references works were used: The Chicago Manual of Style (CMS; 17th edition), Words Into Type (3rd edition), and Merriam-Webster’s Collegiate Dictionary (11th edition, online).

This book has been in the making for several years. I wish to thank all of those who have helped in anyway in editing, comments, and contributions to the text of this book.

Stephen Haggard reviewed an early manuscript of this work and made several valuable comments. Steve was with me when I was a director and chairman of Rocky Mountain Bank. We were grooming him to be the next president. Banks always need a succession plan, and Steve was ours. He is now the president, CEO, and director of Metro Phoenix Bank. A more dedicated, hardworking, and honest person is hard to find in the banking world. I am glad to have been working with Steve for so many years and serving with him as a director and at Metro Phoenix Bank. 

My family has been very helpful in many ways. My children grew up in the real estate and lending world and many of them have contributed to reading and editing past versions of the manuscript.

My son Nicholas Hilton was with Hilton Financial Corporation for many years. At the beginning of the Great Recession, he decided he wanted to move to a cooler climate, so off to Denver he and his family went. He is currently an underwriter for a mortgage company and also holds a real estate license in Arizona. Nick helped with organizing and editing the early manuscripts of this work, for which I am grateful.

My son, Jack Hilton II, has helped compile and edit this book, bringing it from the early manuscripts to a finished product. Jack added a lot of content to this book from his personal knowledge and research. Jack is a loan officer at Hilton Financial Corporation and has been with the company for many years. He knows the business inside and out, and I am very grateful for the dedication he has shown on this project.

My son Beau Hilton and daughter, Charli Hilton Hayes, have both reviewed and made comments on earlier manuscripts. Beau is a doctor, currently serving his residency and internship at Vanderbilt, and Charli is currently working at Metro Phoenix Bank. Both are high performers in their fields.

My wife, Marci, has been an inspiration to this work from the beginning. When we were first married, I had to learn to not talk real estate and finance in every conversation. There are a lot more romantic conversations to be spoken than talking shop. Marci can hold her own with any conversation in the subject of real estate or finance, and it is fun to watch and listen. We have five wonderful children. We had three children and then an eight-year gap, and then two more. Marci likes to tell people she was a single mom with the first three children. It took me that long to figure things out and get my head above the water of learning, even though we are never really done learning. Heaven forbid.

---

# A Message from the Author {- #authormessage}

Lending money to others is one of the oldest businesses in the world. You read about it in the Bible and many other ancient books. In this book, we’ll discuss a wide array of investments associated with moneylending and banking. We’ll briefly discuss the history of banking. We’ll talk about the types of banks  extant today. We’ll talk about starting your own bank, whether that will be a large mortgage banking operation, or a small, self-directed lending business. I’ll give you an overview of the common concerns bankers and private lenders deal with daily. We’ll review common ways to protect your investments and how the current laws either enable or limit your investments.

This publication is designed to provide general information about the subject matter covered. Bearing in mind that laws and practices vary from city to city, state to state, and country to country, and also because each individual situation will be different, the reader should consult with appropriate advisors regarding any specific situation. 

The author has taken reasonable precautions in the preparation of this book and believes the material is accurate as of the date it was written. However, neither the author nor the publisher assume any responsibility for any error or omission. Nor can we warrant accuracy against the progress of time. Legislation and industry practices may further change the face of lending with each day that passes. The author and publisher specifically disclaim any liability resulting from the use or application of the information contained in this book. The information in this book is not intended to serve as legal or professional advice related to any individual situation.

With the above legal disclaimer out of the way, we’re free to jump into the fascinating world of moneylending. But first, I’ll tell you about how I got my start in banking and some of the important milestones and anecdotes from my career. 


---
